const STRINGS = {
  loading: { en: "Loading…", es: "Cargando…", pt: "Carregando…", fr: "Chargement…", it: "Caricamento…" },
  statXpTotal: { en: "Total XP", es: "XP total", pt: "XP total", fr: "XP total", it: "XP totali" },
  statBestCombo: { en: "Best combo", es: "Mejor combo", pt: "Melhor combo", fr: "Meilleur combo", it: "Miglior combo" },
  statRounds: { en: "Rounds", es: "Rondas", pt: "Rodadas", fr: "Manches", it: "Round" },
  levelLabel: { en: "Level:", es: "Nivel:", pt: "Nível:", fr: "Niveau :", it: "Livello:" },
  levelAbbrev: { en: "Lvl.", es: "Nv.", pt: "Nv.", fr: "Niv.", it: "Liv." },
  change: { en: "Change", es: "Cambiar", pt: "Mudar", fr: "Changer", it: "Cambia" },
  close: { en: "Close", es: "Cerrar", pt: "Fechar", fr: "Fermer", it: "Chiudi" },
  notSureTakeQuiz: { en: "Not sure? Take the placement quiz", es: "¿No estás seguro? Hacer prueba de nivel", pt: "Não tem certeza? Faça o teste de nível", fr: "Pas sûr ? Faire le test de niveau", it: "Non sei sicuro? Fai il test di livello" },
  readyToAdvance: { en: "Ready to advance to {level}?", es: "¿Listo para subir a {level}?", pt: "Pronto para avançar para {level}?", fr: "Prêt à passer à {level} ?", it: "Pronto a passare a {level}?" },
  yesAdvance: { en: "Yes, advance", es: "Sí, avanzar", pt: "Sim, avançar", fr: "Oui, avancer", it: "Sì, avanza" },
  notYet: { en: "Not yet", es: "Todavía no", pt: "Ainda não", fr: "Pas encore", it: "Non ancora" },
  roundFocus: { en: "Round focus:", es: "Enfoque de la ronda:", pt: "Foco da rodada:", fr: "Focus de la manche :", it: "Focus del round:" },
  mixed: { en: "Mixed", es: "Mixto", pt: "Misto", fr: "Mixte", it: "Misto" },
  // #88: theme filter (tag layer across categories)
  // Section toggle (Practice | Listen | Speak). These four keys were referenced by
  // app/play, app/learn and ComingSoonSection but never existed in this table, so
  // t() fell through to returning the key and users saw the literal "sectionPractice".
  sectionPractice: { en: "Practice", es: "Practicar", pt: "Praticar", fr: "S'entraîner", it: "Esercitati" },
  sectionListen: { en: "Listen", es: "Escuchar", pt: "Ouvir", fr: "Écouter", it: "Ascolta" },
  sectionSpeak: { en: "Speak", es: "Hablar", pt: "Falar", fr: "Parler", it: "Parla" },
  soonTag: { en: "soon", es: "pronto", pt: "em breve", fr: "bientôt", it: "presto" },
  whatsOnThisPage: { en: "What's on this page?", es: "¿Qué hay en esta página?", pt: "O que tem nesta página?", fr: "Qu'y a-t-il sur cette page ?", it: "Cosa c'è in questa pagina?" },
  reviewBadgeLabel: { en: "Community review in progress", es: "Revisión de la comunidad en curso", pt: "Revisão da comunidade em andamento", fr: "Relecture par la communauté en cours", it: "Revisione della community in corso" },
  homeGreeting: { en: "Welcome", es: "¡Bienvenido/a", pt: "Bem-vindo(a)", fr: "Bienvenue", it: "Benvenuto/a" },
  themeFocus: { en: "Theme (optional):", es: "Tema (opcional):", pt: "Tema (opcional):", fr: "Thème (facultatif) :", it: "Tema (facoltativo):" },
  allThemes: { en: "All themes", es: "Todos los temas", pt: "Todos os temas", fr: "Tous les thèmes", it: "Tutti i temi" },
  // #88 combined focus (category ∩ theme) viability note
  comboReady: { en: "{n} items match your focus + theme.", es: "{n} elementos coinciden con tu enfoque + tema.", pt: "{n} itens combinam com seu foco + tema.", fr: "{n} éléments correspondent à ton focus + thème.", it: "{n} elementi corrispondono al tuo focus + tema." },
  comboThin: { en: "Too few items match focus + theme ({n}) — the round will use the whole theme instead.", es: "Muy pocos elementos coinciden con enfoque + tema ({n}) — la ronda usará todo el tema en su lugar.", pt: "Poucos itens combinam com foco + tema ({n}) — a rodada vai usar o tema inteiro em vez disso.", fr: "Trop peu d'éléments correspondent au focus + thème ({n}) — la manche utilisera le thème entier à la place.", it: "Troppo pochi elementi corrispondono a focus + tema ({n}) — il round userà invece tutto il tema." },
  masteryLabel: { en: "Progress by category:", es: "Progreso por categoría:", pt: "Progresso por categoria:", fr: "Progression par catégorie :", it: "Progressi per categoria:" },
  viewDetails: { en: "View details", es: "Ver detalles", pt: "Ver detalhes", fr: "Voir les détails", it: "Vedi i dettagli" },
  learnedOf: { en: "{learned}/{total} learned", es: "{learned}/{total} aprendidos", pt: "{learned}/{total} aprendidos", fr: "{learned}/{total} appris", it: "{learned}/{total} imparati" },
  startRound: { en: "START ROUND", es: "EMPEZAR RONDA", pt: "COMEÇAR RODADA", fr: "COMMENCER LA MANCHE", it: "INIZIA IL ROUND" },
  reviewMistakes: { en: "REVIEW MISTAKES", es: "REPASAR FALLOS", pt: "REVISAR ERROS", fr: "REVOIR LES ERREURS", it: "RIVEDI GLI ERRORI" },
  viewExplanations: { en: "View explanations ({n})", es: "Ver explicaciones ({n})", pt: "Ver explicações ({n})", fr: "Voir les explications ({n})", it: "Vedi le spiegazioni ({n})" },
  exit: { en: "Exit", es: "Salir", pt: "Sair", fr: "Quitter", it: "Esci" },
  timeUp: { en: "Time's up — no answer was recorded.", es: "Se acabó el tiempo — no se registró ninguna respuesta.", pt: "O tempo acabou — nenhuma resposta foi registrada.", fr: "Temps écoulé — aucune réponse n'a été enregistrée.", it: "Tempo scaduto — nessuna risposta registrata." },
  noAnswer: { en: "No answer given", es: "No respondiste", pt: "Sem resposta", fr: "Pas de réponse", it: "Nessuna risposta" },
  next: { en: "Next", es: "Siguiente", pt: "Próximo", fr: "Suivant", it: "Avanti" },
  wrongNoteHeader: { en: "Heads up", es: "Ojo", pt: "Atenção", fr: "Attention", it: "Attenzione" },
  reviewComplete: { en: "REVIEW COMPLETE", es: "REPASO COMPLETO", pt: "REVISÃO CONCLUÍDA", fr: "RÉVISION TERMINÉE", it: "RIPASSO COMPLETATO" },
  roundComplete: { en: "ROUND COMPLETE", es: "RONDA COMPLETA", pt: "RODADA CONCLUÍDA", fr: "MANCHE TERMINÉE", it: "ROUND COMPLETATO" },
  statCorrect: { en: "Correct", es: "Correctas", pt: "Corretas", fr: "Correctes", it: "Corrette" },
  statXpEarned: { en: "XP earned", es: "XP ganado", pt: "XP ganho", fr: "XP gagnés", it: "XP guadagnati" },
  statMistakesResolved: { en: "Mistakes resolved", es: "Fallos resueltos", pt: "Erros resolvidos", fr: "Erreurs corrigées", it: "Errori risolti" },
  statDailyStreak: { en: "Daily streak", es: "Racha diaria", pt: "Sequência diária", fr: "Série quotidienne", it: "Serie giornaliera" },
  anotherRound: { en: "ANOTHER ROUND", es: "OTRA RONDA", pt: "OUTRA RODADA", fr: "UNE AUTRE MANCHE", it: "UN ALTRO ROUND" },
  backToStart: { en: "Back to start", es: "Volver al inicio", pt: "Voltar ao início", fr: "Retour au début", it: "Torna all'inizio" },
  explanationsTitle: { en: "EXPLANATIONS", es: "EXPLICACIONES", pt: "EXPLICAÇÕES", fr: "EXPLICATIONS", it: "SPIEGAZIONI" },
  explanationsSubtitle: {
    en: "Your recent history — builds up with every round. No timer.",
    es: "Tu historial reciente — se acumula con cada ronda. Sin cronómetro.",
    pt: "Seu histórico recente — cresce a cada rodada. Sem cronômetro.",
    fr: "Ton historique récent — il s'enrichit à chaque manche. Sans chrono.",
    it: "La tua cronologia recente — cresce a ogni round. Senza timer.",
  },
  noExplanationsYet: { en: "No explanations yet — play a round first.", es: "Aún no hay explicaciones — juega una ronda primero.", pt: "Ainda não há explicações — jogue uma rodada primeiro.", fr: "Pas encore d'explications — joue d'abord une manche.", it: "Ancora nessuna spiegazione — gioca prima un round." },
  viewArchive: { en: "View archive ({n})", es: "Ver archivo ({n})", pt: "Ver arquivo ({n})", fr: "Voir les archives ({n})", it: "Vedi l'archivio ({n})" },
  clearAll: { en: "Clear everything (history + archive)", es: "Limpiar todo (historial + archivo)", pt: "Limpar tudo (histórico + arquivo)", fr: "Tout effacer (historique + archives)", it: "Cancella tutto (cronologia + archivio)" },
  archiveTitle: { en: "ARCHIVE", es: "ARCHIVO", pt: "ARQUIVO", fr: "ARCHIVES", it: "ARCHIVIO" },
  archiveSubtitle: { en: "Older explanations.", es: "Explicaciones más antiguas.", pt: "Explicações mais antigas.", fr: "Explications plus anciennes.", it: "Spiegazioni più vecchie." },
  archiveEmpty: { en: "The archive is empty.", es: "El archivo está vacío.", pt: "O arquivo está vazio.", fr: "Les archives sont vides.", it: "L'archivio è vuoto." },
  loadMore: { en: "Load more", es: "Cargar más", pt: "Carregar mais", fr: "Charger plus", it: "Carica altro" },
  backToHistory: { en: "Back to history", es: "Volver al historial", pt: "Voltar ao histórico", fr: "Retour à l'historique", it: "Torna alla cronologia" },
  soundLegend: {
    en: "CAPS = the stressed syllable · ‿ = words blend together in fast speech",
    es: "MAYÚSCULAS = sílaba con más fuerza · ‿ = las palabras se unen al hablar rápido",
    pt: "MAIÚSCULAS = a sílaba tônica · ‿ = as palavras se juntam na fala rápida",
    fr: "MAJUSCULES = la syllabe accentuée · ‿ = les mots se lient quand on parle vite",
    it: "MAIUSCOLE = la sillaba accentata · ‿ = le parole si uniscono nel parlato veloce",
  },
  yourAnswer: { en: "— your answer", es: "— tu respuesta", pt: "— sua resposta", fr: "— ta réponse", it: "— la tua risposta" },
  chooseLesson: { en: "Choose a topic to work through:", es: "Elige un tema para repasar:", pt: "Escolha um tópico para trabalhar:", fr: "Choisis un sujet à travailler :", it: "Scegli un argomento da affrontare:" },
  startLesson: { en: "START LESSON", es: "EMPEZAR LECCIÓN", pt: "COMEÇAR LIÇÃO", fr: "COMMENCER LA LEÇON", it: "INIZIA LA LEZIONE" },
  lessonComplete: { en: "LESSON COMPLETE", es: "LECCIÓN COMPLETA", pt: "LIÇÃO CONCLUÍDA", fr: "LEÇON TERMINÉE", it: "LEZIONE COMPLETATA" },
  backToLessons: { en: "Back to topics", es: "Volver a los temas", pt: "Voltar aos tópicos", fr: "Retour aux sujets", it: "Torna agli argomenti" },
  itemProgress: { en: "Item {current} of {total}", es: "Elemento {current} de {total}", pt: "Item {current} de {total}", fr: "Élément {current} sur {total}", it: "Elemento {current} di {total}" },
  switchToQuickQuiz: { en: "Prefer quick, game-style rounds instead?", es: "¿Prefieres rondas rápidas y con puntos?", pt: "Prefere rodadas rápidas, estilo jogo?", fr: "Tu préfères des manches rapides façon jeu ?", it: "Preferisci round rapidi in stile gioco?" },
  switchToLessons: { en: "Prefer a calmer, step-by-step approach?", es: "¿Prefieres un enfoque más tranquilo, paso a paso?", pt: "Prefere uma abordagem mais tranquila, passo a passo?", fr: "Tu préfères une approche plus calme, pas à pas ?", it: "Preferisci un approccio più tranquillo, passo dopo passo?" },
  tryLessonsMode: { en: "Try Lessons mode", es: "Prueba el modo Lecciones", pt: "Experimente o modo Lições", fr: "Essaie le mode Leçons", it: "Prova la modalità Lezioni" },
  tryQuickQuiz: { en: "Try Quick Quiz mode", es: "Prueba el modo Quiz Rápido", pt: "Experimente o modo Quiz Rápido", fr: "Essaie le mode Quiz Rapide", it: "Prova la modalità Quiz Rapido" },
  modeQuickQuiz: { en: "Quick Quiz", es: "Quiz Rápido", pt: "Quiz Rápido", fr: "Quiz Rapide", it: "Quiz Rapido" },
  modeLessons: { en: "Lessons", es: "Lecciones", pt: "Lições", fr: "Leçons", it: "Lezioni" },
  modeGrammar: { en: "Grammar", es: "Gramática", pt: "Gramática", fr: "Grammaire", it: "Grammatica" },
  // Placement flow (#72 partial / tester bug 2026-07-11): the entire
  // placement flow renders in the person's NATIVE language, always — it's
  // where true beginners land, so target-language chrome is exactly wrong.
  // en/es coverage now (matching the rest of this table); the other eight
  // families ride the #72 sweep.
  placementNoTimer: { en: "no timer", es: "sin cronómetro", pt: "sem cronômetro", fr: "sans chrono", it: "senza timer" },
  placementResult: { en: "Result", es: "Resultado", pt: "Resultado", fr: "Résultat", it: "Risultato" },
  placementRecommended: { en: "Recommended level:", es: "Nivel recomendado:", pt: "Nível recomendado:", fr: "Niveau recommandé :", it: "Livello consigliato:" },
  placementUseLevel: { en: "USE THIS LEVEL", es: "USAR ESTE NIVEL", pt: "USAR ESTE NÍVEL", fr: "UTILISER CE NIVEAU", it: "USA QUESTO LIVELLO" },
  placementBackNoSave: { en: "Go back without saving", es: "Volver sin guardar", pt: "Voltar sem salvar", fr: "Revenir sans enregistrer", it: "Torna indietro senza salvare" },
  placementNotEnough: {
    en: "This track doesn't have enough difficulty-tagged content yet for a placement quiz. Pick a level manually instead.",
    es: "Este idioma aún no tiene suficiente contenido etiquetado por dificultad para una prueba de nivel. Elige un nivel manualmente.",
    pt: "Este idioma ainda não tem conteúdo suficiente marcado por dificuldade para um teste de nível. Escolha um nível manualmente.",
    fr: "Cette langue n'a pas encore assez de contenu étiqueté par difficulté pour un test de niveau. Choisis plutôt un niveau manuellement.",
    it: "Questo percorso non ha ancora abbastanza contenuti etichettati per difficoltà per un test di livello. Scegli un livello a mano.",
  },
  placementBack: { en: "Back", es: "Volver", pt: "Voltar", fr: "Retour", it: "Indietro" },
  // #U1 (2026-07-22): resume-in-progress prompt. en/es now (matching the rest of
  // the placement chrome); the other eight families ride the #72 sweep.
  placementResumeTitle: { en: "Welcome back", es: "¡Hola de nuevo!", pt: "Bem-vindo de volta", fr: "Te revoilà !", it: "Bentornato/a" },
  placementResumeBody: {
    en: "You already started this placement test — you were on question {current} of {total}. Pick up where you left off, or start fresh. Either way, nothing is lost.",
    es: "Ya empezaste esta prueba de nivel — ibas por la pregunta {current} de {total}. Continúa donde lo dejaste o empieza de nuevo. En ambos casos no se pierde nada.",
    pt: "Você já começou este teste de nível — estava na pergunta {current} de {total}. Continue de onde parou ou recomece. De qualquer forma, nada se perde.",
    fr: "Tu as déjà commencé ce test de niveau — tu en étais à la question {current} sur {total}. Reprends où tu t'es arrêté, ou recommence depuis le début. Dans les deux cas, rien n'est perdu.",
    it: "Hai già iniziato questo test di livello — eri alla domanda {current} di {total}. Riprendi da dove eri rimasto o ricomincia. In entrambi i casi non perdi nulla.",
  },
  placementResumeContinue: { en: "Continue where I left off", es: "Continuar donde lo dejé", pt: "Continuar de onde parei", fr: "Reprendre où je me suis arrêté", it: "Riprendi da dove ero rimasto" },
  placementResumeRestart: { en: "Start fresh", es: "Empezar de nuevo", pt: "Recomeçar", fr: "Recommencer depuis le début", it: "Ricomincia" },
  // #62 script practice mode (kana pilot). Chrome is native-language by
  // nature — the audience is people who can't read the target script yet.
  modeScript: { en: "Alphabet", es: "Alfabeto", pt: "Alfabeto", fr: "Alphabet", it: "Alfabeto" },
  scriptLearnTab: { en: "Learn", es: "Aprender", pt: "Aprender", fr: "Apprendre", it: "Impara" },
  scriptPracticeTab: { en: "Practice", es: "Practicar", pt: "Praticar", fr: "S'entraîner", it: "Esercitati" },
  scriptFamiliar: { en: "{n}/{total} familiar", es: "{n}/{total} conocidos", pt: "{n}/{total} conhecidos", fr: "{n}/{total} connus", it: "{n}/{total} noti" },
  scriptWhichSound: { en: "Which sound is this?", es: "¿Qué sonido es este?", pt: "Que som é este?", fr: "Quel son est-ce ?", it: "Che suono è questo?" },
  scriptWhichGlyph: { en: "Which symbol makes this sound?", es: "¿Qué símbolo hace este sonido?", pt: "Qual símbolo faz este som?", fr: "Quel symbole fait ce son ?", it: "Quale simbolo fa questo suono?" },
  scriptCheckAnswers: { en: "Practice these groups", es: "Practicar estos grupos", pt: "Praticar estes grupos", fr: "S'entraîner sur ces groupes", it: "Esercitati con questi gruppi" },
  scriptRoundDone: { en: "NICE PRACTICE!", es: "¡BUENA PRÁCTICA!", pt: "BOA PRÁTICA!", fr: "BIEN JOUÉ !", it: "BELL'ESERCIZIO!" },
  scriptGoAgain: { en: "PRACTICE AGAIN", es: "PRACTICAR OTRA VEZ", pt: "PRATICAR DE NOVO", fr: "S'ENTRAÎNER ENCORE", it: "ESERCITATI ANCORA" },
  scriptBackToLearn: { en: "Back to the charts", es: "Volver a las tablas", pt: "Voltar às tabelas", fr: "Retour aux tableaux", it: "Torna alle tabelle" },
  scriptAllGroups: { en: "All groups", es: "Todos los grupos", pt: "Todos os grupos", fr: "Tous les groupes", it: "Tutti i gruppi" },
  scriptNoticeTitle: { en: "New to {script}?", es: "¿Nuevo con {script}?", pt: "Novo em {script}?", fr: "Nouveau avec {script} ?", it: "Nuovo con {script}?" },
  scriptNotice: {
    en: "Learning the writing system first makes everything else easier — there's a whole practice mode for it, whenever you want it.",
    es: "Aprender primero el sistema de escritura facilita todo lo demás — hay un modo de práctica dedicado, cuando quieras.",
    pt: "Aprender o sistema de escrita primeiro facilita todo o resto — há um modo de prática só para isso, quando você quiser.",
    fr: "Apprendre d'abord le système d'écriture facilite tout le reste — il y a un mode d'entraînement dédié, quand tu veux.",
    it: "Imparare prima il sistema di scrittura rende tutto il resto più facile — c'è una modalità di esercizio dedicata, quando vuoi.",
  },
  scriptNoticeCta: { en: "Check it out", es: "Ver el modo", pt: "Dar uma olhada", fr: "Voir le mode", it: "Dai un'occhiata" },
  scriptNoticeDismiss: { en: "Maybe later", es: "Quizás luego", pt: "Talvez depois", fr: "Peut-être plus tard", it: "Forse dopo" },
  // Home hub — the hub always renders in the person's own native language (it's
  // pre-track, before any immersion level applies). es/en now; other source
  // families ride the #72 sweep.
  quickWin: { en: "Pick your next quick win ⚡", es: "Elige tu próxima victoria ⚡", pt: "Escolha sua próxima vitória rápida ⚡", fr: "Choisis ta prochaine victoire rapide ⚡", it: "Scegli la tua prossima vittoria rapida ⚡" },
  trackNotStarted: { en: "Not started", es: "Sin empezar", pt: "Não iniciado", fr: "Pas commencé", it: "Non iniziato" },
  trackLevelChip: { en: "Level {level} · {skill}", es: "Nivel {level} · {skill}", pt: "Nível {level} · {skill}", fr: "Niveau {level} · {skill}", it: "Livello {level} · {skill}" },
  homeNoNativeHint: {
    en: "Showing every track for now — set your native language in Settings to personalize this list.",
    es: "Mostrando todos los idiomas por ahora — configura tu idioma nativo en Ajustes para personalizar esta lista.",
    pt: "Mostrando todos os idiomas por enquanto — defina seu idioma nativo em Configurações para personalizar esta lista.",
    fr: "Toutes les langues sont affichées pour l'instant — indique ta langue maternelle dans les Réglages pour personnaliser cette liste.",
    it: "Per ora mostriamo tutti i percorsi — imposta la tua lingua madre nelle Impostazioni per personalizzare questa lista.",
  },
  // #72: nav / settings drawer chrome
  navWhatsNew: { en: "What's New", es: "Novedades", pt: "Novidades", fr: "Nouveautés", it: "Novità" },
  navHowToUse: { en: "How to use SquirreLingo", es: "Cómo usar SquirreLingo", pt: "Como usar o SquirreLingo", fr: "Comment utiliser SquirreLingo", it: "Come usare SquirreLingo" },
  navAbout: { en: "About", es: "Acerca de", pt: "Sobre", fr: "À propos", it: "Informazioni" },
  navAdmin: { en: "Admin", es: "Administración", pt: "Administração", fr: "Administration", it: "Amministrazione" },
  navSettingsHeader: { en: "SETTINGS", es: "AJUSTES", pt: "CONFIGURAÇÕES", fr: "RÉGLAGES", it: "IMPOSTAZIONI" },
  navMenu: { en: "Menu", es: "Menú", pt: "Menu", fr: "Menu", it: "Menu" },
  navOpenMenu: { en: "Open menu", es: "Abrir menú", pt: "Abrir menu", fr: "Ouvrir le menu", it: "Apri il menu" },
  navCloseMenu: { en: "Close menu", es: "Cerrar menú", pt: "Fechar menu", fr: "Fermer le menu", it: "Chiudi il menu" },
  // #92 shared Back / Home chrome (BackHome), localized across all pages.
  navBack: { en: "Back", es: "Volver", pt: "Voltar", fr: "Retour", it: "Indietro" },
  navHome: { en: "Home", es: "Inicio", pt: "Início", fr: "Accueil", it: "Home" },
  // #72 changelog / what's new
  clTitle: { en: "Changelog", es: "Registro de cambios", pt: "Registro de mudanças", fr: "Journal des modifications", it: "Registro delle modifiche" },
  clCurrentlyPublished: { en: "Currently published:", es: "Versión actual:", pt: "Versão atual:", fr: "Version actuelle :", it: "Versione attuale:" },
  wnTitle: { en: "What's new", es: "Novedades", pt: "Novidades", fr: "Nouveautés", it: "Novità" },
  wnSeeFullChangelog: { en: "See full changelog", es: "Ver el registro completo", pt: "Ver registro completo", fr: "Voir le journal complet", it: "Vedi il registro completo" },

  // #72 pre-login flow (auth / forgot / reset / onboarding). These render
  // before native_lang exists, so they use the bootstrap uiLang (lib/uiLang.js).
  // --- auth ---
  authSubSignin: { en: "Sign in to continue", es: "Inicia sesión para continuar", pt: "Entre para continuar", fr: "Connecte-toi pour continuer", it: "Accedi per continuare" },
  authSubSignup: { en: "Create an account", es: "Crea una cuenta", pt: "Crie uma conta", fr: "Créer un compte", it: "Crea un account" },
  authIdentifier: { en: "Email or username", es: "Correo o nombre de usuario", pt: "E-mail ou nome de usuário", fr: "E-mail ou nom d'utilisateur", it: "Email o nome utente" },
  authPassword: { en: "Password", es: "Contraseña", pt: "Senha", fr: "Mot de passe", it: "Password" },
  authUsername: { en: "Username", es: "Nombre de usuario", pt: "Nome de usuário", fr: "Nom d'utilisateur", it: "Nome utente" },
  authEmail: { en: "Email", es: "Correo electrónico", pt: "E-mail", fr: "E-mail", it: "Email" },
  authConfirmEmail: { en: "Confirm email", es: "Confirmar correo", pt: "Confirmar e-mail", fr: "Confirmer l'e-mail", it: "Conferma l'email" },
  authConfirmPassword: { en: "Confirm password", es: "Confirmar contraseña", pt: "Confirmar senha", fr: "Confirmer le mot de passe", it: "Conferma la password" },
  authBtnSignin: { en: "SIGN IN", es: "INICIAR SESIÓN", pt: "ENTRAR", fr: "SE CONNECTER", it: "ACCEDI" },
  authBtnSignup: { en: "SIGN UP", es: "REGISTRARSE", pt: "CRIAR CONTA", fr: "S'INSCRIRE", it: "REGISTRATI" },
  authForgot: { en: "Forgot password?", es: "¿Olvidaste tu contraseña?", pt: "Esqueceu a senha?", fr: "Mot de passe oublié ?", it: "Password dimenticata?" },
  authSigninHint: {
    en: "You can sign in with either your username or your email — either works.",
    es: "Puedes iniciar sesión con tu nombre de usuario o tu correo — cualquiera funciona.",
    pt: "Você pode entrar com seu nome de usuário ou seu e-mail — qualquer um funciona.",
    fr: "Tu peux te connecter avec ton nom d'utilisateur ou ton e-mail — les deux fonctionnent.",
    it: "Puoi accedere con il tuo nome utente o con la tua email — vanno bene entrambi.",
  },
  authAgreePre: { en: "I agree to the ", es: "Acepto los ", pt: "Concordo com os ", fr: "J'accepte les ", it: "Accetto i " },
  authAgreeTos: { en: "Terms of Service", es: "Términos del servicio", pt: "Termos de Serviço", fr: "Conditions d'utilisation", it: "Termini di servizio" },
  authAgreeMid: { en: " and ", es: " y la ", pt: " e a ", fr: " et la ", it: " e l'" },
  authAgreePp: { en: "Privacy Policy", es: "Política de privacidad", pt: "Política de Privacidade", fr: "Politique de confidentialité", it: "Informativa sulla privacy" },
  authNeedAccount: { en: "Need an account? Sign up", es: "¿Necesitas una cuenta? Regístrate", pt: "Precisa de uma conta? Cadastre-se", fr: "Besoin d'un compte ? Inscris-toi", it: "Non hai un account? Registrati" },
  authHaveAccount: { en: "Already have an account? Sign in", es: "¿Ya tienes una cuenta? Inicia sesión", pt: "Já tem uma conta? Entre", fr: "Tu as déjà un compte ? Connecte-toi", it: "Hai già un account? Accedi" },
  authBetaPre: { en: "Don't have an invite yet? ", es: "¿Aún no tienes invitación? ", pt: "Ainda não tem convite? ", fr: "Pas encore d'invitation ? ", it: "Non hai ancora un invito? " },
  authBetaLink: { en: "Apply to beta test", es: "Solicita ser beta tester", pt: "Candidate-se para testar a beta", fr: "Demande à être bêta-testeur", it: "Candidati come beta tester" },
  authErrEmailMismatch: { en: "Email addresses don't match.", es: "Los correos no coinciden.", pt: "Os e-mails não coincidem.", fr: "Les adresses e-mail ne correspondent pas.", it: "Le email non coincidono." },
  authErrPwMismatch: { en: "Passwords don't match.", es: "Las contraseñas no coinciden.", pt: "As senhas não coincidem.", fr: "Les mots de passe ne correspondent pas.", it: "Le password non coincidono." },
  authErrPwLen: { en: "Password must be at least 6 characters.", es: "La contraseña debe tener al menos 6 caracteres.", pt: "A senha deve ter pelo menos 6 caracteres.", fr: "Le mot de passe doit comporter au moins 6 caractères.", it: "La password deve avere almeno 6 caratteri." },
  authErrUserRequired: { en: "Username is required.", es: "El nombre de usuario es obligatorio.", pt: "O nome de usuário é obrigatório.", fr: "Le nom d'utilisateur est obligatoire.", it: "Il nome utente è obbligatorio." },
  authErrUserLen: { en: "Username must be at least 3 characters.", es: "El nombre de usuario debe tener al menos 3 caracteres.", pt: "O nome de usuário deve ter pelo menos 3 caracteres.", fr: "Le nom d'utilisateur doit comporter au moins 3 caractères.", it: "Il nome utente deve avere almeno 3 caratteri." },
  authErrAgree: {
    en: "You need to agree to the Terms of Service and Privacy Policy to continue.",
    es: "Debes aceptar los Términos del servicio y la Política de privacidad para continuar.",
    pt: "Você precisa concordar com os Termos de Serviço e a Política de Privacidade para continuar.",
    fr: "Tu dois accepter les Conditions d'utilisation et la Politique de confidentialité pour continuer.",
    it: "Devi accettare i Termini di servizio e l'Informativa sulla privacy per continuare.",
  },
  authErrUserTaken: {
    en: "That username is already taken — try Verify above for some available alternatives.",
    es: "Ese nombre de usuario ya está en uso — prueba «Verificar» arriba para ver alternativas disponibles.",
    pt: "Esse nome de usuário já está em uso — use «Verificar» acima para ver algumas alternativas disponíveis.",
    fr: "Ce nom d'utilisateur est déjà pris — essaie « Vérifier » ci-dessus pour voir des alternatives disponibles.",
    it: "Questo nome utente è già in uso — prova «Verifica» qui sopra per vedere alcune alternative disponibili.",
  },
  authErrEmailExists: {
    en: "An account with that email already exists. Try signing in, or use 'Forgot password' if you don't remember your password.",
    es: "Ya existe una cuenta con ese correo. Intenta iniciar sesión, o usa «¿Olvidaste tu contraseña?» si no la recuerdas.",
    pt: "Já existe uma conta com esse e-mail. Tente entrar, ou use 'Esqueceu a senha?' se não lembrar da sua senha.",
    fr: "Un compte avec cet e-mail existe déjà. Essaie de te connecter, ou utilise « Mot de passe oublié ? » si tu ne t'en souviens pas.",
    it: "Esiste già un account con questa email. Prova ad accedere, oppure usa «Password dimenticata» se non la ricordi.",
  },
  authErrEmailExistsShort: {
    en: "An account with that email already exists. Try signing in instead.",
    es: "Ya existe una cuenta con ese correo. Mejor intenta iniciar sesión.",
    pt: "Já existe uma conta com esse e-mail. Tente entrar em vez disso.",
    fr: "Un compte avec cet e-mail existe déjà. Essaie plutôt de te connecter.",
    it: "Esiste già un account con questa email. Prova invece ad accedere.",
  },
  authErrInvalidCreds: { en: "Invalid login credentials.", es: "Credenciales incorrectas.", pt: "Credenciais inválidas.", fr: "Identifiants incorrects.", it: "Credenziali di accesso non valide." },
  authErrGeneric: { en: "Something went wrong.", es: "Algo salió mal.", pt: "Algo deu errado.", fr: "Quelque chose s'est mal passé.", it: "Qualcosa è andato storto." },
  authInfoConfirm: {
    en: "Check your email to confirm your account, then sign in.",
    es: "Revisa tu correo para confirmar tu cuenta y luego inicia sesión.",
    pt: "Verifique seu e-mail para confirmar sua conta e depois entre.",
    fr: "Consulte ta boîte mail pour confirmer ton compte, puis connecte-toi.",
    it: "Controlla la tua email per confermare l'account, poi accedi.",
  },
  // --- onboarding ---
  obLangTitle: { en: "What's your native language?", es: "¿Cuál es tu idioma nativo?", pt: "Qual é o seu idioma nativo?", fr: "Quelle est ta langue maternelle ?", it: "Qual è la tua lingua madre?" },
  obLangSub: { en: "This decides which languages show up for you to learn.", es: "Esto define qué idiomas aparecen para que aprendas.", pt: "Isso define quais idiomas aparecem para você aprender.", fr: "C'est ce qui détermine les langues qui te seront proposées.", it: "Questo determina quali lingue compaiono per te da imparare." },
  obSearchLang: { en: "Search languages…", es: "Buscar idiomas…", pt: "Buscar idiomas…", fr: "Rechercher une langue…", it: "Cerca lingue…" },
  obContinue: { en: "Continue", es: "Continuar", pt: "Continuar", fr: "Continuer", it: "Continua" },
  obCountryTitle: { en: "What's your native country?", es: "¿Cuál es tu país de origen?", pt: "Qual é o seu país de origem?", fr: "Quel est ton pays d'origine ?", it: "Qual è il tuo paese d'origine?" },
  obCountrySub: {
    en: "Optional — personalizes a little flag/region tag on your home screen.",
    es: "Opcional — personaliza una pequeña etiqueta de bandera/región en tu pantalla de inicio.",
    pt: "Opcional — personaliza uma pequena etiqueta de bandeira/região na sua tela inicial.",
    fr: "Facultatif — personnalise un petit badge drapeau/région sur ton écran d'accueil.",
    it: "Facoltativo — personalizza una piccola etichetta bandiera/regione sulla tua schermata iniziale.",
  },
  obSearchCountry: { en: "Search countries…", es: "Buscar países…", pt: "Buscar países…", fr: "Rechercher un pays…", it: "Cerca paesi…" },
  obSkip: { en: "Skip", es: "Omitir", pt: "Pular", fr: "Passer", it: "Salta" },
  obPicTitle: { en: "Pick a profile picture", es: "Elige una foto de perfil", pt: "Escolha uma foto de perfil", fr: "Choisis une photo de profil", it: "Scegli una foto profilo" },
  obPicSub: {
    en: "Optional — a photo, a fun icon, or a flag. You can change this anytime in Settings.",
    es: "Opcional — una foto, un ícono divertido o una bandera. Puedes cambiarlo cuando quieras en Ajustes.",
    pt: "Opcional — uma foto, um ícone divertido ou uma bandeira. Você pode mudar isso quando quiser em Configurações.",
    fr: "Facultatif — une photo, une icône rigolote ou un drapeau. Tu peux changer ça quand tu veux dans les Réglages.",
    it: "Facoltativo — una foto, un'icona simpatica o una bandiera. Puoi cambiarla quando vuoi nelle Impostazioni.",
  },
  obTabPhoto: { en: "Photo", es: "Foto", pt: "Foto", fr: "Photo", it: "Foto" },
  obTabIcon: { en: "Icon", es: "Ícono", pt: "Ícone", fr: "Icône", it: "Icona" },
  obTabFlag: { en: "Flag", es: "Bandera", pt: "Bandeira", fr: "Drapeau", it: "Bandiera" },
  obChooseFile: { en: "Choose file…", es: "Elegir archivo…", pt: "Escolher arquivo…", fr: "Choisir un fichier…", it: "Scegli un file…" },
  obFinish: { en: "Finish", es: "Finalizar", pt: "Concluir", fr: "Terminer", it: "Fine" },
  // --- forgot / reset password ---
  fpResetTitle: { en: "Reset your password", es: "Restablece tu contraseña", pt: "Redefina sua senha", fr: "Réinitialise ton mot de passe", it: "Reimposta la password" },
  fpEmailSub: {
    en: "Enter your account email. If security questions are set up for the account, they'll appear next.",
    es: "Ingresa el correo de tu cuenta. Si hay preguntas de seguridad configuradas, aparecerán a continuación.",
    pt: "Digite o e-mail da sua conta. Se houver perguntas de segurança configuradas, elas aparecerão em seguida.",
    fr: "Saisis l'e-mail de ton compte. Si des questions de sécurité sont configurées, elles apparaîtront ensuite.",
    it: "Inserisci l'email del tuo account. Se ci sono domande di sicurezza impostate, compariranno subito dopo.",
  },
  fpEmailPh: { en: "Your email", es: "Tu correo", pt: "Seu e-mail", fr: "Ton e-mail", it: "La tua email" },
  fpContinue: { en: "CONTINUE", es: "CONTINUAR", pt: "CONTINUAR", fr: "CONTINUER", it: "CONTINUA" },
  fpBackToSignin: { en: "Back to sign in", es: "Volver a iniciar sesión", pt: "Voltar para entrar", fr: "Retour à la connexion", it: "Torna all'accesso" },
  fpQuestionsSub: {
    en: "Answer your security questions — at least 2 of 3 must match. Answers aren't case-sensitive.",
    es: "Responde tus preguntas de seguridad — al menos 2 de 3 deben coincidir. Las respuestas no distinguen mayúsculas.",
    pt: "Responda suas perguntas de segurança — pelo menos 2 de 3 devem coincidir. As respostas não diferenciam maiúsculas de minúsculas.",
    fr: "Réponds à tes questions de sécurité — au moins 2 sur 3 doivent correspondre. Les réponses ne tiennent pas compte des majuscules.",
    it: "Rispondi alle tue domande di sicurezza — almeno 2 su 3 devono coincidere. Le risposte non distinguono maiuscole e minuscole.",
  },
  fpHintLabel: { en: "Your password hint:", es: "Tu pista de contraseña:", pt: "Sua dica de senha:", fr: "Ton indice de mot de passe :", it: "Il tuo suggerimento per la password:" },
  fpRememberedPre: { en: "(Remembered it? ", es: "(¿La recordaste? ", pt: "(Lembrou? ", fr: "(Ça te revient ? ", it: "(Te la ricordi? " },
  fpGoSignin: { en: "Go sign in", es: "Inicia sesión", pt: "Entrar", fr: "Connecte-toi", it: "Accedi" },
  fpRememberedPost: { en: " instead.)", es: " en su lugar.)", pt: " em vez disso.)", fr: " directement.)", it: " invece.)" },
  fpCheckAnswers: { en: "CHECK ANSWERS", es: "VERIFICAR RESPUESTAS", pt: "VERIFICAR RESPOSTAS", fr: "VÉRIFIER LES RÉPONSES", it: "VERIFICA LE RISPOSTE" },
  fpCantRemember: { en: "Can't remember? Request an admin reset", es: "¿No la recuerdas? Solicita un restablecimiento por un administrador", pt: "Não lembra? Solicite uma redefinição por um administrador", fr: "Tu ne t'en souviens pas ? Demande une réinitialisation à un administrateur", it: "Non la ricordi? Richiedi un reset a un amministratore" },
  fpNoQuestions: {
    en: "This account doesn't have security questions set up, so it can't self-serve a reset.",
    es: "Esta cuenta no tiene preguntas de seguridad configuradas, así que no puede restablecerse por sí sola.",
    pt: "Esta conta não tem perguntas de segurança configuradas, então não é possível redefinir por conta própria.",
    fr: "Ce compte n'a pas de questions de sécurité configurées, il ne peut donc pas être réinitialisé en autonomie.",
    it: "Questo account non ha domande di sicurezza impostate, quindi non può reimpostare la password da solo.",
  },
  fpAdminPre: {
    en: "If the hint doesn't help, an admin can set a temporary password for you — request one below, then check back by trying to sign in later.",
    es: "Si la pista no ayuda, un administrador puede crear una contraseña temporal — solicítala abajo y vuelve a intentar iniciar sesión más tarde.",
    pt: "Se a dica não ajudar, um administrador pode criar uma senha temporária para você — solicite uma abaixo e depois tente entrar novamente mais tarde.",
    fr: "Si l'indice ne t'aide pas, un administrateur peut créer un mot de passe temporaire pour toi — demandes-en un ci-dessous, puis réessaie de te connecter plus tard.",
    it: "Se il suggerimento non basta, un amministratore può creare una password temporanea per te — richiedila qui sotto, poi riprova ad accedere più tardi.",
  },
  fpAdminPreNoHint: {
    en: "An admin can set a temporary password for you — request one below, then check back by trying to sign in later.",
    es: "Un administrador puede crear una contraseña temporal — solicítala abajo y vuelve a intentar iniciar sesión más tarde.",
    pt: "Um administrador pode criar uma senha temporária para você — solicite uma abaixo e depois tente entrar novamente mais tarde.",
    fr: "Un administrateur peut créer un mot de passe temporaire pour toi — demandes-en un ci-dessous, puis réessaie de te connecter plus tard.",
    it: "Un amministratore può creare una password temporanea per te — richiedila qui sotto, poi riprova ad accedere più tardi.",
  },
  fpRequestAdmin: { en: "REQUEST ADMIN RESET", es: "SOLICITAR RESTABLECIMIENTO", pt: "SOLICITAR REDEFINIÇÃO", fr: "DEMANDER UNE RÉINITIALISATION", it: "RICHIEDI IL RESET" },
  fpNewPwSub: { en: "Answers matched — set your new password.", es: "Las respuestas coinciden — define tu nueva contraseña.", pt: "As respostas coincidiram — defina sua nova senha.", fr: "Les réponses correspondent — définis ton nouveau mot de passe.", it: "Le risposte coincidono — imposta la tua nuova password." },
  fpNewPw: { en: "New password", es: "Nueva contraseña", pt: "Nova senha", fr: "Nouveau mot de passe", it: "Nuova password" },
  fpConfirmNewPw: { en: "Confirm new password", es: "Confirmar nueva contraseña", pt: "Confirmar nova senha", fr: "Confirmer le nouveau mot de passe", it: "Conferma la nuova password" },
  fpUpdatePassword: { en: "UPDATE PASSWORD", es: "ACTUALIZAR CONTRASEÑA", pt: "ATUALIZAR SENHA", fr: "METTRE À JOUR LE MOT DE PASSE", it: "AGGIORNA LA PASSWORD" },
  fpDone: { en: "Password updated — taking you to sign in…", es: "Contraseña actualizada — te llevamos a iniciar sesión…", pt: "Senha atualizada — levando você para entrar…", fr: "Mot de passe mis à jour — on t'emmène à la connexion…", it: "Password aggiornata — ti portiamo all'accesso…" },
  fpRequested: {
    en: "Request sent. An admin will set a temporary password for the account if one exists — try signing in again later, and change the temporary password in Settings once you're in.",
    es: "Solicitud enviada. Un administrador creará una contraseña temporal para la cuenta si existe — vuelve a intentar iniciar sesión más tarde y cambia la contraseña temporal en Ajustes cuando entres.",
    pt: "Solicitação enviada. Um administrador criará uma senha temporária para a conta, se ela existir — tente entrar novamente mais tarde e mude a senha temporária em Configurações assim que entrar.",
    fr: "Demande envoyée. Un administrateur créera un mot de passe temporaire pour le compte s'il existe — réessaie de te connecter plus tard, et change le mot de passe temporaire dans les Réglages une fois connecté.",
    it: "Richiesta inviata. Se l'account esiste, un amministratore creerà una password temporanea — riprova ad accedere più tardi e cambia la password temporanea nelle Impostazioni una volta entrato.",
  },
  fpErrExpired: {
    en: "Something went wrong. The reset link may have expired — request a new one.",
    es: "Algo salió mal. Es posible que el enlace de restablecimiento haya caducado — solicita uno nuevo.",
    pt: "Algo deu errado. O link de redefinição pode ter expirado — solicite um novo.",
    fr: "Quelque chose s'est mal passé. Le lien de réinitialisation a peut-être expiré — demandes-en un nouveau.",
    it: "Qualcosa è andato storto. Il link di reimpostazione potrebbe essere scaduto — richiedine uno nuovo.",
  },
  rpSetTitle: { en: "Set a new password", es: "Define una nueva contraseña", pt: "Defina uma nova senha", fr: "Définis un nouveau mot de passe", it: "Imposta una nuova password" },

  // #72 settings drawer (post-login SettingsPanel). Rendered in the person's
  // native language (session.user.user_metadata.native_lang). es/en now;
  // other source families ride the #72 sweep. Spanish is the #41-approved
  // es-LatAm map from the settings-drawer i18n preview.
  // --- group headers / titles ---
  setDrawerTitle: { en: "Settings", es: "Ajustes", pt: "Configurações", fr: "Réglages", it: "Impostazioni" },
  setGroupProfile: { en: "Profile", es: "Perfil", pt: "Perfil", fr: "Profil", it: "Profilo" },
  setGroupAccount: { en: "Account", es: "Cuenta", pt: "Conta", fr: "Compte", it: "Account" },
  setGroupLang: { en: "Language & Learning", es: "Idioma y aprendizaje", pt: "Idioma e aprendizado", fr: "Langue et apprentissage", it: "Lingua e apprendimento" },
  setGroupSub: { en: "Subscription", es: "Suscripción", pt: "Assinatura", fr: "Abonnement", it: "Abbonamento" },
  setGroupFeedback: { en: "Feedback", es: "Comentarios", pt: "Comentários", fr: "Commentaires", it: "Feedback" },
  setTitlePic: { en: "Profile picture", es: "Foto de perfil", pt: "Foto de perfil", fr: "Photo de profil", it: "Foto profilo" },
  setTitleUsername: { en: "Username", es: "Nombre de usuario", pt: "Nome de usuário", fr: "Nom d'utilisateur", it: "Nome utente" },
  setTitleEmail: { en: "Email", es: "Correo electrónico", pt: "E-mail", fr: "E-mail", it: "Email" },
  setTitlePassword: { en: "Password", es: "Contraseña", pt: "Senha", fr: "Mot de passe", it: "Password" },
  setTitleRecovery: { en: "Password recovery", es: "Recuperación de contraseña", pt: "Recuperação de senha", fr: "Récupération du mot de passe", it: "Recupero della password" },
  setTitleNative: { en: "Native / base language", es: "Idioma nativo / base", pt: "Idioma nativo / base", fr: "Langue maternelle / de base", it: "Lingua madre / di base" },
  setTitleCountry: { en: "Native country", es: "País de origen", pt: "País de origem", fr: "Pays d'origine", it: "Paese d'origine" },
  setTitleGameplay: { en: "Gameplay", es: "Juego", pt: "Jogabilidade", fr: "Jeu", it: "Gioco" },
  // --- buttons / generic ---
  setBtnEdit: { en: "Edit", es: "Editar", pt: "Editar", fr: "Modifier", it: "Modifica" },
  setBtnSave: { en: "Save", es: "Guardar", pt: "Salvar", fr: "Enregistrer", it: "Salva" },
  setBtnCancel: { en: "Cancel", es: "Cancelar", pt: "Cancelar", fr: "Annuler", it: "Annulla" },
  setBtnBusy: { en: "...", es: "...", pt: "...", fr: "...", it: "..." },
  setSaved: { en: "Saved.", es: "Guardado.", pt: "Salvo.", fr: "Enregistré.", it: "Salvato." },
  setNotSet: { en: "(not set)", es: "(sin configurar)", pt: "(não definido)", fr: "(non défini)", it: "(non impostato)" },
  // --- profile picture ---
  setTabPhoto: { en: "Photo", es: "Foto", pt: "Foto", fr: "Photo", it: "Foto" },
  setTabIcon: { en: "Icon", es: "Ícono", pt: "Ícone", fr: "Icône", it: "Icona" },
  setTabFlag: { en: "Flag", es: "Bandera", pt: "Bandeira", fr: "Drapeau", it: "Bandiera" },
  setBtnChooseFile: { en: "Choose file…", es: "Elegir archivo…", pt: "Escolher arquivo…", fr: "Choisir un fichier…", it: "Scegli un file…" },
  setPhSearchCountry: { en: "Search countries…", es: "Buscar países…", pt: "Buscar países…", fr: "Rechercher un pays…", it: "Cerca paesi…" },
  setPhUsername: { en: "Username", es: "Nombre de usuario", pt: "Nome de usuário", fr: "Nom d'utilisateur", it: "Nome utente" },
  setAvatarPhoto: { en: "Custom photo", es: "Foto personalizada", pt: "Foto personalizada", fr: "Photo personnalisée", it: "Foto personalizzata" },
  setAvatarFlag: { en: "Flag", es: "Bandera", pt: "Bandeira", fr: "Drapeau", it: "Bandiera" },
  setAvatarIcon: { en: "Icon", es: "Ícono", pt: "Ícone", fr: "Icône", it: "Icona" },
  setErrPhotoSize: { en: "Photo must be under 3MB.", es: "La foto debe pesar menos de 3 MB.", pt: "A foto deve ter menos de 3 MB.", fr: "La photo doit peser moins de 3 Mo.", it: "La foto deve pesare meno di 3 MB." },
  setErrPickIcon: { en: "Pick an icon.", es: "Elige un ícono.", pt: "Escolha um ícone.", fr: "Choisis une icône.", it: "Scegli un'icona." },
  setErrPickFlag: { en: "Pick a flag.", es: "Elige una bandera.", pt: "Escolha uma bandeira.", fr: "Choisis un drapeau.", it: "Scegli una bandiera." },
  setErrChoosePhoto: { en: "Choose a photo to upload.", es: "Elige una foto para subir.", pt: "Escolha uma foto para enviar.", fr: "Choisis une photo à envoyer.", it: "Scegli una foto da caricare." },
  setErrGeneric: { en: "Something went wrong.", es: "Algo salió mal.", pt: "Algo deu errado.", fr: "Quelque chose s'est mal passé.", it: "Qualcosa è andato storto." },
  // --- username ---
  setErrUsernameEmpty: { en: "Username can't be empty.", es: "El nombre de usuario no puede estar vacío.", pt: "O nome de usuário não pode ficar vazio.", fr: "Le nom d'utilisateur ne peut pas être vide.", it: "Il nome utente non può essere vuoto." },
  setErrUsernameTaken: { en: "That username is already taken.", es: "Ese nombre de usuario ya está en uso.", pt: "Esse nome de usuário já está em uso.", fr: "Ce nom d'utilisateur est déjà pris.", it: "Questo nome utente è già in uso." },
  // --- email ---
  setPhNewEmail: { en: "New email", es: "Nuevo correo", pt: "Novo e-mail", fr: "Nouvel e-mail", it: "Nuova email" },
  setPhConfirmEmail: { en: "Confirm new email", es: "Confirmar nuevo correo", pt: "Confirmar novo e-mail", fr: "Confirmer le nouvel e-mail", it: "Conferma la nuova email" },
  setPhCurPwConfirm: { en: "Current password (to confirm it's you)", es: "Contraseña actual (para confirmar que eres tú)", pt: "Senha atual (para confirmar que é você)", fr: "Mot de passe actuel (pour confirmer que c'est bien toi)", it: "Password attuale (per confermare che sei tu)" },
  setNoteEmailSaved: { en: "Check your new email to confirm the change.", es: "Revisa tu nuevo correo para confirmar el cambio.", pt: "Verifique seu novo e-mail para confirmar a mudança.", fr: "Consulte ta nouvelle boîte mail pour confirmer le changement.", it: "Controlla la tua nuova email per confermare la modifica." },
  setErrEmailsMismatch: { en: "Emails don't match.", es: "Los correos no coinciden.", pt: "Os e-mails não coincidem.", fr: "Les e-mails ne correspondent pas.", it: "Le email non coincidono." },
  setErrCurPwRequired: { en: "Enter your current password to confirm this change.", es: "Ingresa tu contraseña actual para confirmar este cambio.", pt: "Digite sua senha atual para confirmar esta mudança.", fr: "Saisis ton mot de passe actuel pour confirmer ce changement.", it: "Inserisci la tua password attuale per confermare questa modifica." },
  setErrCurPwWrong: { en: "Current password is incorrect.", es: "La contraseña actual es incorrecta.", pt: "A senha atual está incorreta.", fr: "Le mot de passe actuel est incorrect.", it: "La password attuale non è corretta." },
  // --- password ---
  setPhCurPw: { en: "Current password", es: "Contraseña actual", pt: "Senha atual", fr: "Mot de passe actuel", it: "Password attuale" },
  setPhNewPw: { en: "New password", es: "Nueva contraseña", pt: "Nova senha", fr: "Nouveau mot de passe", it: "Nuova password" },
  setPhConfirmPw: { en: "Confirm new password", es: "Confirmar nueva contraseña", pt: "Confirmar nova senha", fr: "Confirmer le nouveau mot de passe", it: "Conferma la nuova password" },
  setNotePwSaved: { en: "Other signed-in devices have been logged out for security.", es: "Se cerró la sesión en los demás dispositivos por seguridad.", pt: "Os outros dispositivos conectados foram desconectados por segurança.", fr: "Les autres appareils connectés ont été déconnectés par sécurité.", it: "Gli altri dispositivi collegati sono stati disconnessi per sicurezza." },
  setErrPwLen: { en: "New password must be at least 6 characters.", es: "La nueva contraseña debe tener al menos 6 caracteres.", pt: "A nova senha deve ter pelo menos 6 caracteres.", fr: "Le nouveau mot de passe doit comporter au moins 6 caractères.", it: "La nuova password deve avere almeno 6 caratteri." },
  setErrPwMismatch: { en: "New passwords don't match.", es: "Las nuevas contraseñas no coinciden.", pt: "As novas senhas não coincidem.", fr: "Les nouveaux mots de passe ne correspondent pas.", it: "Le nuove password non coincidono." },
  // --- password recovery ---
  setRecNotSetUp: { en: "Not set up", es: "Sin configurar", pt: "Não configurado", fr: "Non configurée", it: "Non impostato" },
  setRecStatusQuestions: { en: "{n} security questions on file", es: "{n} preguntas de seguridad guardadas", pt: "{n} perguntas de segurança salvas", fr: "{n} questions de sécurité enregistrées", it: "{n} domande di sicurezza salvate" },
  setRecHintSuffix: { en: " · hint set", es: " · pista configurada", pt: " · dica configurada", fr: " · indice défini", it: " · suggerimento impostato" },
  setRecStatusHintOnly: { en: "Hint set · no security questions yet", es: "Pista configurada · aún sin preguntas de seguridad", pt: "Dica configurada · ainda sem perguntas de segurança", fr: "Indice défini · pas encore de questions de sécurité", it: "Suggerimento impostato · ancora nessuna domanda di sicurezza" },
  setRecNoteNone: {
    en: "Without security questions, a forgotten password means waiting on an admin reset — setting them up takes a minute and lets you reset it yourself.",
    es: "Sin preguntas de seguridad, si olvidas tu contraseña tendrás que esperar a que un administrador la restablezca — configurarlas toma un minuto y te permite restablecerla tú mismo.",
    pt: "Sem perguntas de segurança, esquecer a senha significa esperar por uma redefinição do administrador — configurá-las leva um minuto e permite que você mesmo a redefina.",
    fr: "Sans questions de sécurité, un mot de passe oublié veut dire attendre qu'un administrateur le réinitialise — les configurer prend une minute et te permet de le réinitialiser toi-même.",
    it: "Senza domande di sicurezza, se dimentichi la password devi aspettare il reset di un amministratore — impostarle richiede un minuto e ti permette di reimpostarla da solo.",
  },
  setRecNoteEdit: {
    en: "The hint shows to anyone who enters your email on the reset page — make it useful to you, useless to others. Answers aren't case-sensitive, but spelling counts. For your security, saved answers are never shown again — re-entering all three replaces the old set; leaving all three empty changes only the hint.",
    es: "La pista se muestra a cualquiera que ingrese tu correo en la página de restablecimiento — hazla útil para ti e inútil para los demás. Las respuestas no distinguen mayúsculas, pero la ortografía cuenta. Por tu seguridad, las respuestas guardadas no se vuelven a mostrar — volver a ingresar las tres reemplaza el conjunto anterior; dejar las tres vacías cambia solo la pista.",
    pt: "A dica aparece para qualquer pessoa que digite seu e-mail na página de redefinição — faça-a útil para você e inútil para os outros. As respostas não diferenciam maiúsculas de minúsculas, mas a ortografia conta. Por sua segurança, as respostas salvas nunca são mostradas de novo — digitar as três novamente substitui o conjunto anterior; deixar as três vazias muda apenas a dica.",
    fr: "L'indice s'affiche pour toute personne qui saisit ton e-mail sur la page de réinitialisation — rends-le utile pour toi et inutile pour les autres. Les réponses ne tiennent pas compte des majuscules, mais l'orthographe compte. Pour ta sécurité, les réponses enregistrées ne sont jamais réaffichées — ressaisir les trois remplace l'ancien jeu ; laisser les trois vides ne change que l'indice.",
    it: "Il suggerimento viene mostrato a chiunque inserisca la tua email nella pagina di reimpostazione — rendilo utile per te e inutile per gli altri. Le risposte non distinguono maiuscole e minuscole, ma l'ortografia conta. Per la tua sicurezza, le risposte salvate non vengono mai più mostrate — reinserirle tutte e tre sostituisce il set precedente; lasciarle tutte e tre vuote cambia solo il suggerimento.",
  },
  setErrRecoveryIncomplete: {
    en: "Fill in all three questions and answers, or leave all three empty to keep your questions as they are.",
    es: "Completa las tres preguntas y respuestas, o deja las tres vacías para mantener tus preguntas como están.",
    pt: "Preencha as três perguntas e respostas, ou deixe as três vazias para manter suas perguntas como estão.",
    fr: "Remplis les trois questions et réponses, ou laisse les trois vides pour garder tes questions telles quelles.",
    it: "Compila tutte e tre le domande e risposte, oppure lasciale tutte e tre vuote per mantenere le tue domande così come sono.",
  },
  setErrRecoveryDupes: { en: "Pick three different questions.", es: "Elige tres preguntas diferentes.", pt: "Escolha três perguntas diferentes.", fr: "Choisis trois questions différentes.", it: "Scegli tre domande diverse." },
  setPhHint: { en: "Password hint (optional)", es: "Pista de contraseña (opcional)", pt: "Dica de senha (opcional)", fr: "Indice de mot de passe (facultatif)", it: "Suggerimento per la password (facoltativo)" },
  setPhAnswer: { en: "Answer", es: "Respuesta", pt: "Resposta", fr: "Réponse", it: "Risposta" },
  setOptQuestion: { en: "— Question {n} —", es: "— Pregunta {n} —", pt: "— Pergunta {n} —", fr: "— Question {n} —", it: "— Domanda {n} —" },
  setAriaHint: { en: "Password hint", es: "Pista de contraseña", pt: "Dica de senha", fr: "Indice de mot de passe", it: "Suggerimento per la password" },
  setAriaSecurityQuestion: { en: "Security question {n}", es: "Pregunta de seguridad {n}", pt: "Pergunta de segurança {n}", fr: "Question de sécurité {n}", it: "Domanda di sicurezza {n}" },
  setAriaAnswer: { en: "Answer to security question {n}", es: "Respuesta a la pregunta de seguridad {n}", pt: "Resposta à pergunta de segurança {n}", fr: "Réponse à la question de sécurité {n}", it: "Risposta alla domanda di sicurezza {n}" },
  // --- native language / country ---
  setPhSearchLang: { en: "Search languages…", es: "Buscar idiomas…", pt: "Buscar idiomas…", fr: "Rechercher une langue…", it: "Cerca lingue…" },
  setNativeNote: {
    en: "Changing this only changes which languages show up to learn — progress in tracks you've already played is kept.",
    es: "Cambiar esto solo cambia qué idiomas aparecen para aprender — se conserva tu progreso en los idiomas que ya jugaste.",
    pt: "Mudar isso só muda quais idiomas aparecem para aprender — seu progresso nos idiomas que você já jogou é mantido.",
    fr: "Changer ça ne change que les langues proposées à l'apprentissage — ta progression dans les langues déjà jouées est conservée.",
    it: "Cambiarlo modifica solo quali lingue compaiono da imparare — i progressi nei percorsi che hai già giocato restano.",
  },
  setNeedNativeFirst: { en: "Set your native language above first.", es: "Primero define tu idioma nativo arriba.", pt: "Defina seu idioma nativo acima primeiro.", fr: "Définis d'abord ta langue maternelle ci-dessus.", it: "Prima imposta la tua lingua madre qui sopra." },
  setCountryNote: {
    en: "Combined with your native language, this determines the regional label shown on the home screen (e.g. Spanish + Venezuela → \"Español (Latinoamérica)\").",
    es: "Junto con tu idioma nativo, esto determina la etiqueta regional que se muestra en la pantalla de inicio (p. ej. español + Venezuela → \"Español (Latinoamérica)\").",
    pt: "Combinado com seu idioma nativo, isso determina a etiqueta regional mostrada na tela inicial (ex.: espanhol + Venezuela → \"Español (Latinoamérica)\").",
    fr: "Combiné à ta langue maternelle, ceci détermine l'étiquette régionale affichée sur l'écran d'accueil (p. ex. français + Canada → « Français (Canada) »).",
    it: "Insieme alla tua lingua madre, questo determina l'etichetta regionale mostrata sulla schermata iniziale (ad es. spagnolo + Venezuela → \"Español (Latinoamérica)\").",
  },
  // --- gameplay ---
  setGpReviewOn: { en: "Review mode: on", es: "Modo repaso: activado", pt: "Modo revisão: ativado", fr: "Mode révision : activé", it: "Modalità ripasso: attiva" },
  setGpReviewOff: { en: "Review mode: off", es: "Modo repaso: desactivado", pt: "Modo revisão: desativado", fr: "Mode révision : désactivé", it: "Modalità ripasso: disattivata" },
  setGpSummary: {
    en: "{perCat} questions/category · {pairs} phonetics pairs · question audio {qAudio} · answer-choice audio {cAudio} · tense hints {tHints} · {time}s{phon} per question",
    es: "{perCat} preguntas/categoría · {pairs} pares de fonética · audio de pregunta {qAudio} · audio de opciones {cAudio} · pistas de tiempo verbal {tHints} · {time}s{phon} por pregunta",
    pt: "{perCat} perguntas/categoria · {pairs} pares de fonética · áudio da pergunta {qAudio} · áudio das opções {cAudio} · dicas de tempo verbal {tHints} · {time}s{phon} por pergunta",
    fr: "{perCat} questions/catégorie · {pairs} paires de phonétique · audio de la question {qAudio} · audio des options {cAudio} · indications de temps verbal {tHints} · {time}s{phon} par question",
    it: "{perCat} domande/categoria · {pairs} coppie di fonetica · audio della domanda {qAudio} · audio delle opzioni {cAudio} · suggerimenti sui tempi verbali {tHints} · {time}s{phon} per domanda",
  },
  setGpOn: { en: "on", es: "activado", pt: "ativado", fr: "activé", it: "attivo" },
  setGpOff: { en: "off", es: "desactivado", pt: "desativado", fr: "désactivé", it: "disattivo" },
  setGpOnF: { en: "on", es: "activadas", pt: "ativadas", fr: "activées", it: "attivi" },
  setGpOffF: { en: "off", es: "desactivadas", pt: "desativadas", fr: "désactivées", it: "disattivi" },
  setGpSummaryPhon: { en: " ({time}s phonetics)", es: " ({time}s fonética)", pt: " ({time}s fonética)", fr: " ({time}s phonétique)", it: " ({time}s fonetica)" },
  setGpTogReview: {
    en: "Pause after each answer to review the explanation (tap \"Next\" to continue)",
    es: "Pausar después de cada respuesta para repasar la explicación (toca \"Siguiente\" para continuar)",
    pt: "Pausar após cada resposta para revisar a explicação (toque em \"Próximo\" para continuar)",
    fr: "Faire une pause après chaque réponse pour lire l'explication (touche « Suivant » pour continuer)",
    it: "Metti in pausa dopo ogni risposta per rivedere la spiegazione (tocca \"Avanti\" per continuare)",
  },
  setGpTogQaudio: {
    en: "Show a speaker button on questions that have audio (tap to hear the prompt read aloud — never plays automatically)",
    es: "Mostrar un botón de altavoz en las preguntas que tienen audio (toca para escuchar la consigna en voz alta — nunca se reproduce solo)",
    pt: "Mostrar um botão de alto-falante nas perguntas que têm áudio (toque para ouvir o enunciado em voz alta — nunca toca sozinho)",
    fr: "Afficher un bouton haut-parleur sur les questions qui ont de l'audio (touche pour écouter la consigne à voix haute — ne se lance jamais tout seul)",
    it: "Mostra un pulsante altoparlante sulle domande che hanno audio (tocca per ascoltare la consegna letta ad alta voce — non parte mai da solo)",
  },
  setGpTogCaudio: {
    en: "Show a speaker button on the answer choices too — only after you've answered (in review/pause), tap to hear an option read aloud. Rolling out per track; appears where option audio exists.",
    es: "Mostrar un botón de altavoz también en las opciones de respuesta — solo después de responder (en repaso/pausa), toca para escuchar una opción en voz alta. Se habilita por pista; aparece donde hay audio de opciones.",
    pt: "Mostrar um botão de alto-falante também nas opções de resposta — só depois de responder (na revisão/pausa), toque para ouvir uma opção em voz alta. Sendo liberado por idioma; aparece onde há áudio das opções.",
    fr: "Afficher aussi un bouton haut-parleur sur les options de réponse — seulement après avoir répondu (en révision/pause), touche pour écouter une option à voix haute. Déployé langue par langue ; apparaît là où l'audio des options existe.",
    it: "Mostra un pulsante altoparlante anche sulle opzioni di risposta — solo dopo che hai risposto (in ripasso/pausa), tocca per ascoltare un'opzione letta ad alta voce. In arrivo percorso per percorso; compare dove esiste l'audio delle opzioni.",
  },
  setGpTogTense: {
    en: "Tense training-wheels: on verb-conjugation questions, name the tense being asked for and why. On by default; you can also dismiss it in-round once you reach an advanced level.",
    es: "Rueditas de apoyo para tiempos verbales: en las preguntas de conjugación, indica qué tiempo se pide y por qué. Activado por defecto; también puedes ocultarlo durante la ronda al llegar a un nivel avanzado.",
    pt: "Rodinhas de apoio para tempos verbais: nas perguntas de conjugação, indica qual tempo está sendo pedido e por quê. Ativado por padrão; você também pode dispensá-lo durante a rodada ao chegar a um nível avançado.",
    fr: "Roues d'appoint pour les temps verbaux : sur les questions de conjugaison, indique quel temps est demandé et pourquoi. Activé par défaut ; tu peux aussi le masquer en pleine manche une fois arrivé à un niveau avancé.",
    it: "Rotelle di supporto per i tempi verbali: nelle domande di coniugazione, indica quale tempo viene chiesto e perché. Attivo di default; puoi anche nasconderlo durante il round quando raggiungi un livello avanzato.",
  },
  setGpPerCat: { en: "Questions per category (mixed rounds)", es: "Preguntas por categoría (rondas mixtas)", pt: "Perguntas por categoria (rodadas mistas)", fr: "Questions par catégorie (manches mixtes)", it: "Domande per categoria (round misti)" },
  setGpPairs: { en: "Phonetics pairs per round", es: "Pares de fonética por ronda", pt: "Pares de fonética por rodada", fr: "Paires de phonétique par manche", it: "Coppie di fonetica per round" },
  setGpSameTimer: { en: "Same time limit for every question type", es: "Mismo límite de tiempo para todos los tipos de pregunta", pt: "Mesmo limite de tempo para todos os tipos de pergunta", fr: "Même limite de temps pour tous les types de question", it: "Stesso limite di tempo per ogni tipo di domanda" },
  setGpSecSame: { en: "Seconds per question", es: "Segundos por pregunta", pt: "Segundos por pergunta", fr: "Secondes par question", it: "Secondi per domanda" },
  setGpSecRegular: { en: "Seconds (regular)", es: "Segundos (normal)", pt: "Segundos (normal)", fr: "Secondes (normal)", it: "Secondi (normale)" },
  setGpSecPhon: { en: "Seconds (phonetics)", es: "Segundos (fonética)", pt: "Segundos (fonética)", fr: "Secondes (phonétique)", it: "Secondi (fonetica)" },
  // --- subscription / feedback / footer ---
  setComingSoon: { en: "Coming soon.", es: "Próximamente.", pt: "Em breve.", fr: "Bientôt disponible.", it: "Prossimamente." },
  setFbBug: { en: "🐞 Report a bug", es: "🐞 Reportar un error", pt: "🐞 Relatar um erro", fr: "🐞 Signaler un bug", it: "🐞 Segnala un bug" },
  setFbFeature: { en: "💡 Suggest a feature", es: "💡 Sugerir una función", pt: "💡 Sugerir um recurso", fr: "💡 Suggérer une fonctionnalité", it: "💡 Proponi una funzione" },
  setSignOut: { en: "Sign out", es: "Cerrar sesión", pt: "Sair", fr: "Se déconnecter", it: "Esci" },
  setTos: { en: "Terms of Service", es: "Términos del servicio", pt: "Termos de Serviço", fr: "Conditions d'utilisation", it: "Termini di servizio" },
  setPrivacy: { en: "Privacy Policy", es: "Política de privacidad", pt: "Política de Privacidade", fr: "Politique de confidentialité", it: "Informativa sulla privacy" },

  // #72 beta-apply (pre-login flow; renders before native_lang exists, so it
  // uses the bootstrap uiLang — lib/uiLang.js). Spanish is AI-authored, written
  // gender-neutral (no "/a" forms), pending #41 native review. Option-set values
  // stay English canonical (the stored/POSTed value); only the label is localized.
  baTitle: { en: "Apply to beta test", es: "Solicita ser beta tester", pt: "Candidate-se para testar a beta", fr: "Demande à être bêta-testeur", it: "Candidati come beta tester" },
  baSubtitle: {
    en: "Takes about 3 minutes. Tell us about you and how you like to practice.",
    es: "Toma unos 3 minutos. Cuéntanos sobre ti y cómo te gusta practicar.",
    pt: "Leva cerca de 3 minutos. Conte-nos sobre você e como gosta de praticar.",
    fr: "Ça prend environ 3 minutes. Parle-nous de toi et de ta façon de t'entraîner.",
    it: "Ci vogliono circa 3 minuti. Raccontaci di te e di come ti piace esercitarti.",
  },
  baStepAboutYou: { en: "About You", es: "Sobre ti", pt: "Sobre você", fr: "À propos de toi", it: "Su di te" },
  baStepLangBg: { en: "Language Background", es: "Tu experiencia con idiomas", pt: "Sua experiência com idiomas", fr: "Ton expérience avec les langues", it: "La tua esperienza con le lingue" },
  baStepHabits: { en: "Practice Habits & Fit", es: "Hábitos de práctica y afinidad", pt: "Hábitos de prática e afinidade", fr: "Habitudes d'entraînement et affinité", it: "Abitudini di studio e affinità" },
  baStepCommitment: { en: "Beta Commitment", es: "Compromiso con la beta", pt: "Compromisso com a beta", fr: "Engagement pour la bêta", it: "Impegno per la beta" },
  baStepAccount: { en: "Your Account", es: "Tu cuenta", pt: "Sua conta", fr: "Ton compte", it: "Il tuo account" },
  baBack: { en: "Back", es: "Atrás", pt: "Voltar", fr: "Retour", it: "Indietro" },
  baNext: { en: "Next", es: "Siguiente", pt: "Próximo", fr: "Suivant", it: "Avanti" },
  baSubmit: { en: "Submit application", es: "Enviar solicitud", pt: "Enviar candidatura", fr: "Envoyer la demande", it: "Invia la candidatura" },
  baSending: { en: "Sending...", es: "Enviando...", pt: "Enviando...", fr: "Envoi...", it: "Invio in corso..." },
  baFooterPre: { en: "Already have an account? ", es: "¿Ya tienes una cuenta? ", pt: "Já tem uma conta? ", fr: "Tu as déjà un compte ? ", it: "Hai già un account? " },
  baFooterLink: { en: "Sign in instead", es: "Inicia sesión", pt: "Entre em vez disso", fr: "Connecte-toi plutôt", it: "Accedi" },
  // --- step 0: About You ---
  baFieldName: { en: "Name or nickname", es: "Nombre o apodo", pt: "Nome ou apelido", fr: "Prénom ou surnom", it: "Nome o soprannome" },
  baFieldEmail: { en: "Email", es: "Correo electrónico", pt: "E-mail", fr: "E-mail", it: "Email" },
  baFieldAge: { en: "How old are you?", es: "¿Qué edad tienes?", pt: "Quantos anos você tem?", fr: "Quel âge as-tu ?", it: "Quanti anni hai?" },
  baAgeUnder18: { en: "Under 18", es: "Menos de 18", pt: "Menos de 18", fr: "Moins de 18 ans", it: "Meno di 18" },
  baAge18_24: { en: "18–24", es: "18–24", pt: "18–24", fr: "18–24", it: "18–24" },
  baAge25_34: { en: "25–34", es: "25–34", pt: "25–34", fr: "25–34", it: "25–34" },
  baAge35_44: { en: "35–44", es: "35–44", pt: "35–44", fr: "35–44", it: "35–44" },
  baAge45_54: { en: "45–54", es: "45–54", pt: "45–54", fr: "45–54", it: "45–54" },
  baAge55plus: { en: "55+", es: "55+", pt: "55+", fr: "55+", it: "55+" },
  baFieldDevices: { en: "What device(s) would you test SquirreLingo on?", es: "¿En qué dispositivo(s) probarías SquirreLingo?", pt: "Em qual(is) dispositivo(s) você testaria o SquirreLingo?", fr: "Sur quel(s) appareil(s) testerais-tu SquirreLingo ?", it: "Su quali dispositivi proveresti SquirreLingo?" },
  baDevAndroid: { en: "Android phone", es: "Teléfono Android", pt: "Celular Android", fr: "Téléphone Android", it: "Telefono Android" },
  baDevIphone: { en: "iPhone", es: "iPhone", pt: "iPhone", fr: "iPhone", it: "iPhone" },
  baDevTablet: { en: "Tablet (Android or iPad)", es: "Tablet (Android o iPad)", pt: "Tablet (Android ou iPad)", fr: "Tablette (Android ou iPad)", it: "Tablet (Android o iPad)" },
  baDevDesktop: { en: "Desktop/laptop browser (Windows or Mac)", es: "Navegador de computadora o laptop (Windows o Mac)", pt: "Navegador de computador ou notebook (Windows ou Mac)", fr: "Navigateur sur ordinateur portable ou de bureau (Windows ou Mac)", it: "Browser su computer o portatile (Windows o Mac)" },
  baDevChromebook: { en: "Chromebook", es: "Chromebook", pt: "Chromebook", fr: "Chromebook", it: "Chromebook" },
  baFieldBrowser: { en: "Which browser do you use most on that device?", es: "¿Qué navegador usas más en ese dispositivo?", pt: "Qual navegador você mais usa nesse dispositivo?", fr: "Quel navigateur utilises-tu le plus sur cet appareil ?", it: "Quale browser usi di più su quel dispositivo?" },
  baBrowChrome: { en: "Chrome", es: "Chrome", pt: "Chrome", fr: "Chrome", it: "Chrome" },
  baBrowSafari: { en: "Safari", es: "Safari", pt: "Safari", fr: "Safari", it: "Safari" },
  baBrowFirefox: { en: "Firefox", es: "Firefox", pt: "Firefox", fr: "Firefox", it: "Firefox" },
  baBrowEdge: { en: "Edge", es: "Edge", pt: "Edge", fr: "Edge", it: "Edge" },
  baBrowSamsung: { en: "Samsung Internet", es: "Samsung Internet", pt: "Samsung Internet", fr: "Samsung Internet", it: "Samsung Internet" },
  baBrowOther: { en: "Other", es: "Otro", pt: "Outro", fr: "Autre", it: "Altro" },
  // --- step 1: Language Background ---
  baFieldNative: { en: "What is your native language (or strongest language)?", es: "¿Cuál es tu idioma nativo (o el idioma que dominas mejor)?", pt: "Qual é o seu idioma nativo (ou o idioma que você domina melhor)?", fr: "Quelle est ta langue maternelle (ou ta langue la plus forte) ?", it: "Qual è la tua lingua madre (o la lingua che conosci meglio)?" },
  baFieldTarget: { en: "Which language(s) do you want to practice with SquirreLingo?", es: "¿Qué idioma(s) quieres practicar con SquirreLingo?", pt: "Qual(is) idioma(s) você quer praticar com o SquirreLingo?", fr: "Quelle(s) langue(s) veux-tu pratiquer avec SquirreLingo ?", it: "Quali lingue vuoi praticare con SquirreLingo?" },
  baFieldLevel: { en: "How would you rate your current level in that language?", es: "¿Cómo calificarías tu nivel actual en ese idioma?", pt: "Como você avaliaria seu nível atual nesse idioma?", fr: "Comment évaluerais-tu ton niveau actuel dans cette langue ?", it: "Come valuteresti il tuo livello attuale in quella lingua?" },
  baLvlComplete: { en: "Complete beginner (a few words at most)", es: "Principiante total (unas pocas palabras, como mucho)", pt: "Iniciante total (poucas palavras, no máximo)", fr: "Grand débutant (quelques mots tout au plus)", it: "Principiante assoluto (poche parole al massimo)" },
  baLvlBeginner: { en: "Beginner (basic phrases, simple vocabulary)", es: "Principiante (frases básicas, vocabulario simple)", pt: "Iniciante (frases básicas, vocabulário simples)", fr: "Débutant (phrases de base, vocabulaire simple)", it: "Principiante (frasi di base, vocabolario semplice)" },
  baLvlIntermediate: { en: "Intermediate (can hold simple conversations)", es: "Intermedio (puedo mantener conversaciones sencillas)", pt: "Intermediário (consigo manter conversas simples)", fr: "Intermédiaire (je peux tenir des conversations simples)", it: "Intermedio (riesco a fare conversazioni semplici)" },
  baLvlAdvanced: { en: "Advanced (comfortable in most conversations)", es: "Avanzado (me desenvuelvo bien en la mayoría de las conversaciones)", pt: "Avançado (me viro bem na maioria das conversas)", fr: "Avancé (à l'aise dans la plupart des conversations)", it: "Avanzato (me la cavo bene nella maggior parte delle conversazioni)" },
  baLvlNative: { en: "Native/fluent", es: "Nativo/fluido", pt: "Nativo/fluente", fr: "Natif/courant", it: "Madrelingua/fluente" },
  baFieldDialect: {
    en: "Any preference for a specific regional variety or dialect (e.g. Latin American vs. European Spanish)?",
    es: "¿Tienes preferencia por alguna variedad regional o dialecto en específico (por ejemplo, español latinoamericano vs. europeo)?",
    pt: "Você tem preferência por alguma variedade regional ou dialeto específico (por exemplo, espanhol latino-americano vs. europeu)?",
    fr: "As-tu une préférence pour une variété régionale ou un dialecte en particulier (par exemple français de France vs. français du Québec) ?",
    it: "Hai una preferenza per una varietà regionale o un dialetto specifico (per esempio spagnolo latinoamericano vs. europeo)?",
  },
  baFieldApps: { en: "Which language-learning apps or methods have you used before?", es: "¿Qué apps o métodos para aprender idiomas has usado antes?", pt: "Quais apps ou métodos para aprender idiomas você já usou antes?", fr: "Quelles applis ou méthodes d'apprentissage des langues as-tu déjà utilisées ?", it: "Quali app o metodi per imparare le lingue hai già usato?" },
  baAppDuolingo: { en: "Duolingo", es: "Duolingo", pt: "Duolingo", fr: "Duolingo", it: "Duolingo" },
  baAppBabbel: { en: "Babbel", es: "Babbel", pt: "Babbel", fr: "Babbel", it: "Babbel" },
  baAppRosetta: { en: "Rosetta Stone", es: "Rosetta Stone", pt: "Rosetta Stone", fr: "Rosetta Stone", it: "Rosetta Stone" },
  baAppAnki: { en: "Anki / flashcards", es: "Anki / tarjetas de memoria", pt: "Anki / cartões de memória", fr: "Anki / cartes mémoire", it: "Anki / flashcard" },
  baAppClasses: { en: "Classes or tutoring", es: "Clases o tutorías", pt: "Aulas ou tutoria", fr: "Cours ou soutien scolaire", it: "Corsi o lezioni private" },
  baAppImmersion: { en: "Immersion (family, friends, travel, work)", es: "Inmersión (familia, amistades, viajes, trabajo)", pt: "Imersão (família, amigos, viagens, trabalho)", fr: "Immersion (famille, amis, voyages, travail)", it: "Immersione (famiglia, amici, viaggi, lavoro)" },
  baAppNone: { en: "None — this would be my first", es: "Ninguno — esta sería mi primera vez", pt: "Nenhum — esta seria minha primeira vez", fr: "Aucune — ce serait ma première fois", it: "Nessuno — questa sarebbe la mia prima volta" },
  baFieldFrustration: { en: "What's your biggest frustration with the language apps you've tried?", es: "¿Cuál es tu mayor frustración con las apps de idiomas que has probado?", pt: "Qual é a sua maior frustração com os apps de idiomas que você já experimentou?", fr: "Quelle est ta plus grande frustration avec les applis de langues que tu as essayées ?", it: "Qual è la tua frustrazione più grande con le app di lingue che hai provato?" },
  // --- step 2: Practice Habits & Fit ---
  baFieldFrequency: { en: "How often do you realistically see yourself practicing?", es: "Siendo realista, ¿con qué frecuencia te ves practicando?", pt: "Sendo realista, com que frequência você se vê praticando?", fr: "Concrètement, à quelle fréquence te vois-tu t'entraîner ?", it: "Realisticamente, con che frequenza pensi di esercitarti?" },
  baFreqMulti: { en: "Multiple times a day", es: "Varias veces al día", pt: "Várias vezes por dia", fr: "Plusieurs fois par jour", it: "Più volte al giorno" },
  baFreqDaily: { en: "Once a day", es: "Una vez al día", pt: "Uma vez por dia", fr: "Une fois par jour", it: "Una volta al giorno" },
  baFreqFewWeek: { en: "A few times a week", es: "Unas cuantas veces por semana", pt: "Algumas vezes por semana", fr: "Quelques fois par semaine", it: "Qualche volta a settimana" },
  baFreqWeekly: { en: "Once a week", es: "Una vez por semana", pt: "Uma vez por semana", fr: "Une fois par semaine", it: "Una volta a settimana" },
  baFreqSporadic: { en: "Sporadically", es: "De vez en cuando", pt: "De vez em quando", fr: "De temps en temps", it: "Ogni tanto" },
  baFieldSessionLen: { en: "How long is your ideal practice session?", es: "¿Cuánto dura tu sesión de práctica ideal?", pt: "Qual é a duração da sua sessão de prática ideal?", fr: "Quelle est la durée idéale d'une séance d'entraînement pour toi ?", it: "Quanto dura la tua sessione di studio ideale?" },
  baSlenUnder5: { en: "Under 5 minutes", es: "Menos de 5 minutos", pt: "Menos de 5 minutos", fr: "Moins de 5 minutes", it: "Meno di 5 minuti" },
  baSlen5_10: { en: "5–10 minutes", es: "5–10 minutos", pt: "5–10 minutos", fr: "5–10 minutes", it: "5–10 minuti" },
  baSlen10_20: { en: "10–20 minutes", es: "10–20 minutos", pt: "10–20 minutos", fr: "10–20 minutes", it: "10–20 minuti" },
  baSlen20plus: { en: "20+ minutes", es: "Más de 20 minutos", pt: "Mais de 20 minutos", fr: "Plus de 20 minutes", it: "Più di 20 minuti" },
  baFieldAppeal: {
    en: "SquirreLingo uses short rounds, instant feedback, and streak/combo mechanics instead of penalties (plus a calmer no-timer mode). How appealing does that sound?",
    es: "SquirreLingo usa rondas cortas, retroalimentación al instante y mecánicas de rachas y combos en lugar de castigos (además de un modo más tranquilo, sin cronómetro). ¿Qué tan atractivo te suena eso?",
    pt: "O SquirreLingo usa rodadas curtas, feedback instantâneo e mecânicas de sequência e combo em vez de punições (além de um modo mais tranquilo, sem cronômetro). O quão atraente isso soa para você?",
    fr: "SquirreLingo utilise des manches courtes, un retour immédiat et des mécaniques de séries et de combos plutôt que des pénalités (avec aussi un mode plus calme, sans chrono). Est-ce que ça te tente ?",
    it: "SquirreLingo usa round brevi, feedback immediato e meccaniche di serie e combo invece di penalità (più una modalità più tranquilla, senza timer). Quanto ti attira tutto questo?",
  },
  baAppealLow: { en: "Not my style", es: "No es mi estilo", pt: "Não é meu estilo", fr: "Ce n'est pas mon style", it: "Non fa per me" },
  baAppealHigh: { en: "Exactly what I want", es: "Justo lo que busco", pt: "Exatamente o que eu quero", fr: "Exactement ce que je cherche", it: "Esattamente quello che cerco" },
  baFieldFocus: { en: "Do you find it hard to stay focused or consistent with traditional study methods?", es: "¿Se te dificulta mantener la concentración o la constancia con los métodos de estudio tradicionales?", pt: "Você tem dificuldade de manter o foco ou a consistência com métodos de estudo tradicionais?", fr: "As-tu du mal à rester concentré ou régulier avec les méthodes d'étude traditionnelles ?", it: "Fai fatica a mantenere la concentrazione o la costanza con i metodi di studio tradizionali?" },
  baFocusVery: { en: "Yes, very much", es: "Sí, muchísimo", pt: "Sim, muito", fr: "Oui, énormément", it: "Sì, moltissimo" },
  baFocusSomewhat: { en: "Somewhat", es: "Un poco", pt: "Um pouco", fr: "Un peu", it: "Un po'" },
  baFocusNotReally: { en: "Not really", es: "La verdad no", pt: "Nem tanto", fr: "Pas vraiment", it: "Non proprio" },
  baFocusNotSure: { en: "Not sure", es: "No sabría decir", pt: "Não sei dizer", fr: "Je ne saurais pas dire", it: "Non saprei" },
  // --- step 3: Beta Commitment ---
  baFieldCommit: { en: "During the beta period (about 2–4 weeks), how much time could you commit to testing?", es: "Durante el periodo de la beta (unas 2–4 semanas), ¿cuánto tiempo podrías dedicar a las pruebas?", pt: "Durante o período da beta (cerca de 2–4 semanas), quanto tempo você poderia dedicar aos testes?", fr: "Pendant la période de bêta (environ 2 à 4 semaines), combien de temps pourrais-tu consacrer aux tests ?", it: "Durante il periodo di beta (circa 2–4 settimane), quanto tempo potresti dedicare ai test?" },
  baCommitDaily: { en: "15+ minutes most days", es: "15+ minutos casi todos los días", pt: "15+ minutos quase todos os dias", fr: "15 minutes ou plus la plupart des jours", it: "15+ minuti quasi tutti i giorni" },
  baCommitFew: { en: "A few sessions per week", es: "Unas cuantas sesiones por semana", pt: "Algumas sessões por semana", fr: "Quelques séances par semaine", it: "Qualche sessione a settimana" },
  baCommitOneTwo: { en: "One or two sessions per week", es: "Una o dos sesiones por semana", pt: "Uma ou duas sessões por semana", fr: "Une ou deux séances par semaine", it: "Una o due sessioni a settimana" },
  baCommitOccasional: { en: "Only occasional use", es: "Solo uso ocasional", pt: "Apenas uso ocasional", fr: "Une utilisation seulement occasionnelle", it: "Solo un uso occasionale" },
  baFieldPrior: { en: "Have you beta tested apps or software before?", es: "¿Has probado apps o software en beta antes?", pt: "Você já testou apps ou software em beta antes?", fr: "As-tu déjà testé des applis ou des logiciels en bêta ?", it: "Hai già testato app o software in beta?" },
  baPriorSeveral: { en: "Yes, several times", es: "Sí, varias veces", pt: "Sim, várias vezes", fr: "Oui, plusieurs fois", it: "Sì, varie volte" },
  baPriorOnceTwice: { en: "Once or twice", es: "Una o dos veces", pt: "Uma ou duas vezes", fr: "Une ou deux fois", it: "Una o due volte" },
  baPriorFirst: { en: "No, this would be my first", es: "No, esta sería mi primera vez", pt: "Não, esta seria minha primeira vez", fr: "Non, ce serait ma première fois", it: "No, questa sarebbe la mia prima volta" },
  baFieldBugComfort: { en: "How comfortable are you reporting bugs with details (what you did, what happened, screenshots)?", es: "¿Qué tan a gusto te sientes reportando errores con detalles (qué hiciste, qué pasó, capturas de pantalla)?", pt: "O quão à vontade você se sente relatando erros com detalhes (o que fez, o que aconteceu, capturas de tela)?", fr: "À quel point es-tu à l'aise pour signaler des bugs en détail (ce que tu as fait, ce qui s'est passé, captures d'écran) ?", it: "Quanto ti senti a tuo agio a segnalare bug con dettagli (cosa hai fatto, cosa è successo, screenshot)?" },
  baBugLow: { en: "Not comfortable", es: "Nada a gusto", pt: "Nada à vontade", fr: "Pas à l'aise du tout", it: "Per niente a mio agio" },
  baBugHigh: { en: "Very comfortable", es: "Muy a gusto", pt: "Muito à vontade", fr: "Très à l'aise", it: "Molto a mio agio" },
  baFieldReason: { en: "Why do you want to beta test SquirreLingo?", es: "¿Por qué quieres ser beta tester de SquirreLingo?", pt: "Por que você quer ser beta tester do SquirreLingo?", fr: "Pourquoi veux-tu être bêta-testeur de SquirreLingo ?", it: "Perché vuoi fare il beta tester di SquirreLingo?" },
  baFieldAnything: { en: "Anything else we should know about you?", es: "¿Algo más que debamos saber sobre ti?", pt: "Mais alguma coisa que devemos saber sobre você?", fr: "Autre chose que nous devrions savoir sur toi ?", it: "Qualcos'altro che dovremmo sapere su di te?" },
  // --- step 4: Your Account ---
  baAcctIntro: {
    en: "Last step — set up your login. Your account is created the moment you submit, and you'll be signed in right away.",
    es: "Último paso — configura tu inicio de sesión. Tu cuenta se crea en el momento en que envías la solicitud, y tu sesión se inicia de inmediato.",
    pt: "Último passo — configure seu login. Sua conta é criada no momento em que você envia, e você entra na hora.",
    fr: "Dernière étape — configure ta connexion. Ton compte est créé dès l'envoi, et tu seras connecté tout de suite.",
    it: "Ultimo passo — configura il tuo accesso. Il tuo account viene creato nel momento in cui invii, e accedi subito.",
  },
  baFieldUsername: { en: "Pick a username", es: "Elige un nombre de usuario", pt: "Escolha um nome de usuário", fr: "Choisis un nom d'utilisateur", it: "Scegli un nome utente" },
  baUsernameHint: { en: "At least 3 characters — letters, numbers, and _ only.", es: "Al menos 3 caracteres — solo letras, números y _.", pt: "Pelo menos 3 caracteres — apenas letras, números e _.", fr: "Au moins 3 caractères — uniquement des lettres, des chiffres et _.", it: "Almeno 3 caratteri — solo lettere, numeri e _." },
  baFieldPassword: { en: "Choose a password", es: "Elige una contraseña", pt: "Escolha uma senha", fr: "Choisis un mot de passe", it: "Scegli una password" },
  baPhPassword: { en: "Password (min 6 characters)", es: "Contraseña (mínimo 6 caracteres)", pt: "Senha (mínimo 6 caracteres)", fr: "Mot de passe (6 caractères minimum)", it: "Password (minimo 6 caratteri)" },
  baFieldConfirm: { en: "Confirm password", es: "Confirma la contraseña", pt: "Confirme a senha", fr: "Confirme le mot de passe", it: "Conferma la password" },
  baPhConfirm: { en: "Repeat password", es: "Repite la contraseña", pt: "Repita a senha", fr: "Répète le mot de passe", it: "Ripeti la password" },
  baPwNoMatch: { en: "Passwords don't match yet.", es: "Las contraseñas aún no coinciden.", pt: "As senhas ainda não coincidem.", fr: "Les mots de passe ne correspondent pas encore.", it: "Le password non coincidono ancora." },
  baPwMatch: { en: "Passwords match ✓", es: "Las contraseñas coinciden ✓", pt: "As senhas coincidem ✓", fr: "Les mots de passe correspondent ✓", it: "Le password coincidono ✓" },
  baRecoveryLead: { en: "Password recovery (optional, recommended):", es: "Recuperación de contraseña (opcional, recomendada):", pt: "Recuperação de senha (opcional, recomendada):", fr: "Récupération du mot de passe (facultatif, recommandé) :", it: "Recupero della password (facoltativo, consigliato):" },
  baRecoveryBody: {
    en: " we can't email reset links during the beta, so a password hint and three security questions are the only way to reset a forgotten password yourself. Skip them and you'd have to request an admin reset instead. You can also set these up later in Settings.",
    es: " durante la beta no podemos enviar enlaces de restablecimiento por correo, así que una pista de contraseña y tres preguntas de seguridad son la única forma de restablecer por tu cuenta una contraseña olvidada. Si las omites, tendrías que pedirle a un administrador que la restablezca. También puedes configurarlas más adelante en Ajustes.",
    pt: " durante a beta não podemos enviar links de redefinição por e-mail, então uma dica de senha e três perguntas de segurança são a única forma de você mesmo redefinir uma senha esquecida. Se pular, você teria que pedir uma redefinição a um administrador. Você também pode configurá-las depois em Configurações.",
    fr: " pendant la bêta nous ne pouvons pas envoyer de liens de réinitialisation par e-mail, donc un indice de mot de passe et trois questions de sécurité sont le seul moyen de réinitialiser toi-même un mot de passe oublié. Si tu les sautes, il faudrait demander une réinitialisation à un administrateur. Tu peux aussi les configurer plus tard dans les Réglages.",
    it: " durante la beta non possiamo inviare link di reimpostazione via email, quindi un suggerimento per la password e tre domande di sicurezza sono l'unico modo per reimpostare da solo una password dimenticata. Se le salti, dovrai chiedere il reset a un amministratore. Puoi anche configurarle più avanti nelle Impostazioni.",
  },
  baFieldHint: { en: "Password hint", es: "Pista de contraseña", pt: "Dica de senha", fr: "Indice de mot de passe", it: "Suggerimento per la password" },
  baPhHint: { en: "A hint only you understand (shown on the reset page)", es: "Una pista que solo tú entiendas (se muestra en la página de restablecimiento)", pt: "Uma dica que só você entende (mostrada na página de redefinição)", fr: "Un indice que toi seul comprends (affiché sur la page de réinitialisation)", it: "Un suggerimento che capisci solo tu (mostrato nella pagina di reimpostazione)" },
  baSecQLabel: { en: "Security question {n}", es: "Pregunta de seguridad {n}", pt: "Pergunta de segurança {n}", fr: "Question de sécurité {n}", it: "Domanda di sicurezza {n}" },
  baAriaAnswer: { en: "Answer to security question {n}", es: "Respuesta a la pregunta de seguridad {n}", pt: "Resposta à pergunta de segurança {n}", fr: "Réponse à la question de sécurité {n}", it: "Risposta alla domanda di sicurezza {n}" },
  baSecQChoose: { en: "— Choose a question —", es: "— Elige una pregunta —", pt: "— Escolha uma pergunta —", fr: "— Choisis une question —", it: "— Scegli una domanda —" },
  baPhAnswer: { en: "Answer (not case-sensitive)", es: "Respuesta (no distingue mayúsculas de minúsculas)", pt: "Resposta (não diferencia maiúsculas de minúsculas)", fr: "Réponse (majuscules et minuscules indifférentes)", it: "Risposta (non distingue maiuscole e minuscole)" },
  // --- validation ---
  baErrStep0: { en: "Name, email, and at least one device are needed to move on.", es: "Necesitamos tu nombre, tu correo y al menos un dispositivo para continuar.", pt: "Precisamos do seu nome, e-mail e pelo menos um dispositivo para continuar.", fr: "Ton prénom, ton e-mail et au moins un appareil sont nécessaires pour continuer.", it: "Servono nome, email e almeno un dispositivo per andare avanti." },
  baErrStep1: { en: "Your native language, target language(s), and current level are needed to move on.", es: "Necesitamos tu idioma nativo, el/los idioma(s) que quieres practicar y tu nivel actual para continuar.", pt: "Precisamos do seu idioma nativo, do(s) idioma(s) que quer praticar e do seu nível atual para continuar.", fr: "Ta langue maternelle, la ou les langues visées et ton niveau actuel sont nécessaires pour continuer.", it: "Servono la tua lingua madre, le lingue che vuoi imparare e il tuo livello attuale per andare avanti." },
  baErrStep2: { en: "Practice frequency and session length are needed to move on.", es: "Necesitamos tu frecuencia de práctica y la duración de la sesión para continuar.", pt: "Precisamos da sua frequência de prática e da duração da sessão para continuar.", fr: "La fréquence d'entraînement et la durée des séances sont nécessaires pour continuer.", it: "Servono la frequenza di studio e la durata della sessione per andare avanti." },
  baErrStep3: { en: "How much time you could commit is needed to move on.", es: "Necesitamos saber cuánto tiempo podrías dedicar para continuar.", pt: "Precisamos saber quanto tempo você poderia dedicar para continuar.", fr: "Le temps que tu pourrais consacrer est nécessaire pour continuer.", it: "Serve sapere quanto tempo potresti dedicare per andare avanti." },
  baErrUsername: { en: "Username must be at least 3 characters (letters, numbers, and _ only).", es: "El nombre de usuario debe tener al menos 3 caracteres (solo letras, números y _).", pt: "O nome de usuário deve ter pelo menos 3 caracteres (apenas letras, números e _).", fr: "Le nom d'utilisateur doit comporter au moins 3 caractères (uniquement des lettres, des chiffres et _).", it: "Il nome utente deve avere almeno 3 caratteri (solo lettere, numeri e _)." },
  baErrPwLen: { en: "Password must be at least 6 characters.", es: "La contraseña debe tener al menos 6 caracteres.", pt: "A senha deve ter pelo menos 6 caracteres.", fr: "Le mot de passe doit comporter au moins 6 caractères.", it: "La password deve avere almeno 6 caratteri." },
  baErrPwMismatch: { en: "Passwords don't match.", es: "Las contraseñas no coinciden.", pt: "As senhas não coincidem.", fr: "Les mots de passe ne correspondent pas.", it: "Le password non coincidono." },
  baErrSqPartial: { en: "Security questions: fill in all three questions and answers, or leave all three empty to skip.", es: "Preguntas de seguridad: completa las tres preguntas y respuestas, o deja las tres vacías para omitirlas.", pt: "Perguntas de segurança: preencha as três perguntas e respostas, ou deixe as três vazias para pular.", fr: "Questions de sécurité : remplis les trois questions et réponses, ou laisse les trois vides pour les ignorer.", it: "Domande di sicurezza: compila tutte e tre le domande e risposte, oppure lasciale tutte e tre vuote per saltarle." },
  baErrSqDistinct: { en: "Security questions: pick three different questions.", es: "Preguntas de seguridad: elige tres preguntas diferentes.", pt: "Perguntas de segurança: escolha três perguntas diferentes.", fr: "Questions de sécurité : choisis trois questions différentes.", it: "Domande di sicurezza: scegli tre domande diverse." },
  baErrUserTaken: { en: "That username is already taken — try Verify above for available alternatives.", es: "Ese nombre de usuario ya está en uso — prueba «Verificar» arriba para ver alternativas disponibles.", pt: "Esse nome de usuário já está em uso — use «Verificar» acima para ver alternativas disponíveis.", fr: "Ce nom d'utilisateur est déjà pris — essaie « Vérifier » ci-dessus pour voir les alternatives disponibles.", it: "Questo nome utente è già in uso — prova «Verifica» qui sopra per vedere le alternative disponibili." },
  baErrGeneric: { en: "Something went wrong submitting your application — please try again.", es: "Algo salió mal al enviar tu solicitud — inténtalo de nuevo, por favor.", pt: "Algo deu errado ao enviar sua candidatura — tente novamente, por favor.", fr: "Quelque chose s'est mal passé lors de l'envoi de ta demande — réessaie, s'il te plaît.", it: "Qualcosa è andato storto durante l'invio della candidatura — riprova, per favore." },
  // --- success screens ---
  baOkTitle: { en: "You're in! 🐿️", es: "¡Estás dentro! 🐿️", pt: "Você está dentro! 🐿️", fr: "Tu es des nôtres ! 🐿️", it: "Sei dentro! 🐿️" },
  baOkBody1: { en: "Your beta account is ready — sign in with the email and password you just chose.", es: "Tu cuenta de beta está lista — inicia sesión con el correo y la contraseña que acabas de elegir.", pt: "Sua conta beta está pronta — entre com o e-mail e a senha que você acabou de escolher.", fr: "Ton compte bêta est prêt — connecte-toi avec l'e-mail et le mot de passe que tu viens de choisir.", it: "Il tuo account beta è pronto — accedi con l'email e la password che hai appena scelto." },
  baOkBtn: { en: "Go to sign in", es: "Ir a iniciar sesión", pt: "Ir para entrar", fr: "Aller à la connexion", it: "Vai all'accesso" },
  baThanksTitle: { en: "Thanks for applying! 🐿️", es: "¡Gracias por postularte! 🐿️", pt: "Obrigado por se candidatar! 🐿️", fr: "Merci pour ta demande ! 🐿️", it: "Grazie per la candidatura! 🐿️" },
  baThanksBody1: { en: "Your application was received. If you're a good fit for the current round of testing, you'll hear back at the email you provided.", es: "Recibimos tu solicitud. Si encajas bien con la ronda de pruebas actual, te contactaremos al correo que nos diste.", pt: "Recebemos sua candidatura. Se você se encaixar bem na rodada de testes atual, entraremos em contato pelo e-mail que você forneceu.", fr: "Nous avons bien reçu ta demande. Si tu corresponds bien à la vague de tests en cours, nous te répondrons à l'adresse e-mail que tu nous as donnée.", it: "Abbiamo ricevuto la tua candidatura. Se sei adatto al ciclo di test attuale, ti scriveremo all'email che ci hai indicato." },
  baThanksBtn: { en: "Already have an invite? Sign in", es: "¿Ya tienes una invitación? Inicia sesión", pt: "Já tem um convite? Entre", fr: "Tu as déjà une invitation ? Connecte-toi", it: "Hai già un invito? Accedi" },
  baFbPre: { en: "While you're at it: the ", es: "Y de paso: el ", pt: "E já que está por aqui: o ", fr: "Et tant qu'on y est : le ", it: "E già che ci sei: il " },
  baFbLink: { en: "SquirreLingo Facebook group", es: "grupo de SquirreLingo en Facebook", pt: "grupo do SquirreLingo no Facebook", fr: "groupe Facebook de SquirreLingo", it: "gruppo Facebook di SquirreLingo" },
  baFbPost: {
    en: " is where release news and tester chat happen — it's private during the beta, so request to join and you'll be approved.",
    es: " es donde se comparten las novedades de cada versión y se conversa entre testers — es privado durante la beta, así que solicita unirte y te aprobaremos.",
    pt: " é onde as novidades de cada versão e a conversa entre testers acontecem — é privado durante a beta, então solicite para entrar e você será aprovado.",
    fr: " est l'endroit où l'on partage les nouveautés de chaque version et où les testeurs discutent — il est privé pendant la bêta, alors demande à le rejoindre et tu seras accepté.",
    it: " è dove trovi le novità di ogni versione e le chiacchiere tra tester — durante la beta è privato, quindi richiedi di entrare e verrai approvato.",
  },
};

// Skill levels at which UI chrome shows in the person's native language rather
// than the language they're learning — early on, reading instructions in a
// language you don't know yet would just add friction.
const NATIVE_LANG_SKILL_LEVELS = ["none", "beginner", "intermediate"];

// The 4 category concepts every track uses (vocab/grammar/idioms/phonetics)
// mean the same thing regardless of which track they're attached to, so one
// shared translation table covers all 14 tracks at once -- no need for
// per-track native-language category labels.
const CATEGORY_NAMES = {
  vocab: {
    en: "Vocabulary", es: "Vocabulario", it: "Vocabolario", fr: "Vocabulaire", de: "Wortschatz",
    pt: "Vocabulário", ru: "Словарь", ja: "単語", zh: "词汇", ko: "단어",
  },
  gram: {
    en: "Grammar", es: "Gramática", it: "Grammatica", fr: "Grammaire", de: "Grammatik",
    pt: "Gramática", ru: "Грамматика", ja: "文法", zh: "语法", ko: "문법",
  },
  verbo: { en: "Grammar", es: "Verbos", pt: "Verbos", fr: "Verbes", it: "Verbi" }, // esForEn/esSpainForEn's legacy key for the same concept
  trad: {
    en: "Idioms", es: "Modismos", it: "Modi di dire", fr: "Expressions", de: "Redewendungen",
    pt: "Expressões", ru: "Идиомы", ja: "慣用句", zh: "成语", ko: "관용구",
  },
  fono: {
    en: "Phonetics", es: "Fonética", it: "Fonetica", fr: "Phonétique", de: "Phonetik",
    pt: "Fonética", ru: "Фонетика", ja: "発音", zh: "发音", ko: "발음",
  },
  // Frequency word bank (pilot: esForEn, 2026-07-10). Generated from a
  // frequency-ranked word list — see lib/frequencyVocab.js.
  fvocab: {
    en: "Word Bank", es: "Palabras", it: "Parole", fr: "Mots courants", de: "Wortbank",
    pt: "Palavras", ru: "Слова", ja: "頻出単語", zh: "常用词", ko: "빈출 단어",
  },
};

export function uiLangForSkill(skillLevel, viewerNativeLang, track) {
  if (NATIVE_LANG_SKILL_LEVELS.includes(skillLevel)) {
    return viewerNativeLang || track.nativeLang || "en";
  }
  // track.targetLang should always be set; "en" is just a safe universal
  // fallback if it's ever missing, not an assumption nativeLang is en/es.
  return track.targetLang || "en";
}

export function t(lang, key, vars) {
  const entry = STRINGS[key];
  if (!entry) return key;
  let str = entry[lang] || entry.en;
  if (vars) {
    Object.keys(vars).forEach((k) => {
      str = str.replace(`{${k}}`, vars[k]);
    });
  }
  return str;
}

// Category names (Vocabulary/Grammar/Idioms/Phonetics) previously only
// switched language for the narrow English-US/UK cross-dialect case
// (track.cats[catId].labelEn), never for the general skill-level-based
// native-language chrome everything else already respects. This fixes that:
// low-skill viewers see the category name in their own native language;
// higher-skill viewers still see the track's own target-language name
// (immersive, as originally designed).
export function categoryDisplayName(uiLang, viewerNativeLang, track, catId) {
  if (uiLang === viewerNativeLang && CATEGORY_NAMES[catId]) {
    return CATEGORY_NAMES[catId][uiLang] || track.cats[catId].label;
  }
  return track.cats[catId].labelEn && uiLang === "en" ? track.cats[catId].labelEn : track.cats[catId].label;
}
