// AUTO-GENERATED by scripts/gen-track-item-counts.mjs — do not hand-edit the
// counts. Regenerate after any content change with:
//   node scripts/gen-track-item-counts.mjs
//
// Why this file exists: the admin progress dashboard needs to show "coverage"
// (how much of a track a learner has actually seen), which requires the total
// number of learnable items per track. Counting them at request time would mean
// importing the (multi-MB) track data into a serverless function on every call,
// so we bake the totals here instead. Counts include every BANK category plus
// the phonetics (fono) extra-bank pairs — i.e. the full set of seen-trackable
// item ids the engine records (see lib/gameEngine.js: `${cat}-${i}` and
// `${extraCatId}-pair-${i}`).

export const TRACK_ITEM_COUNTS = {
  "de-for-en": { total: 847, categories: { vocab: 134, gram: 494, trad: 135, fono: 84 } },
  "en-for-it": { total: 33, categories: { vocab: 12, gram: 9, trad: 7, fono: 5 } },
  "en-gb-for-es": { total: 12, categories: { vocab: 3, gram: 3, trad: 3, fono: 3 } },
  "en-us-for-es": { total: 11, categories: { vocab: 3, gram: 3, trad: 2, fono: 3 } },
  "es-latam-for-en": { total: 745, categories: { vocab: 134, verbo: 404, trad: 127, fono: 80 } },
  "es-spain-for-en": { total: 851, categories: { vocab: 127, verbo: 517, trad: 127, fono: 80 } },
  "fr-ca-for-en": { total: 968, categories: { vocab: 131, verbo: 642, trad: 118, fono: 77 } },
  "fr-for-en": { total: 1036, categories: { vocab: 152, verbo: 689, trad: 118, fono: 77 } },
  "it-for-en": { total: 981, categories: { vocab: 137, verbo: 659, trad: 104, fono: 81 } },
  "ja-for-en": { total: 823, categories: { vocab: 134, gram: 483, trad: 126, fono: 80 } },
  "ko-for-en": { total: 836, categories: { vocab: 134, gram: 494, trad: 127, fono: 81 } },
  "pt-br-for-en": { total: 1113, categories: { vocab: 133, verbo: 785, trad: 113, fono: 82 } },
  "pt-pt-for-en": { total: 1029, categories: { vocab: 135, verbo: 702, trad: 110, fono: 82 } },
  "ru-for-en": { total: 829, categories: { vocab: 134, gram: 490, trad: 125, fono: 80 } },
  "zh-for-en": { total: 591, categories: { vocab: 134, gram: 249, trad: 127, fono: 81 } },
};

// English display labels for the admin dashboard (admin UI is English-only).
// Kept alongside the counts so the admin API needs no other import.
export const TRACK_LABELS = {
  "es-latam-for-en": "Spanish (Latin America)",
  "es-spain-for-en": "Spanish (Spain)",
  "en-us-for-es": "English (US) · for Spanish speakers",
  "en-gb-for-es": "English (UK) · for Spanish speakers",
  "it-for-en": "Italian",
  "fr-for-en": "French",
  "fr-ca-for-en": "French (Canada)",
  "pt-br-for-en": "Portuguese (Brazil)",
  "pt-pt-for-en": "Portuguese (Portugal)",
  "de-for-en": "German",
  "ru-for-en": "Russian",
  "ja-for-en": "Japanese",
  "zh-for-en": "Mandarin Chinese",
  "ko-for-en": "Korean",
  "en-for-it": "English · for Italian speakers",
};

// Total learnable items for a track, or null if unknown (e.g. a track added
// after this file was last regenerated). Callers should treat null coverage as
// "—" rather than 0%.
export function trackTotalItems(trackId) {
  return TRACK_ITEM_COUNTS[trackId] ? TRACK_ITEM_COUNTS[trackId].total : null;
}

// Item total for a specific category within a track (used for per-category
// coverage), or null if unknown.
export function categoryTotalItems(trackId, cat) {
  const t = TRACK_ITEM_COUNTS[trackId];
  return t && t.categories && typeof t.categories[cat] === "number" ? t.categories[cat] : null;
}

// Friendly label, falling back to the raw id so unknown/future tracks still render.
export function trackLabel(trackId) {
  return TRACK_LABELS[trackId] || trackId;
}
